import { useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import CaseWorkbench from './CaseWorkbench';
import ImportReview from './ImportReview';
import { CaseDraft, newCaseDraft } from './caseTypes';

type Role='viewer'|'author'|'reviewer'|'publisher'|'admin';
type Page='dashboard'|'curriculum'|'content'|'cases'|'uploads';
type Profile={id:string;role:Role;display_name:string|null};
type Organ={id:string;code:string;organ_system_translations:{locale:string;name:string}[]};
type Level={id:string;organ_system_id:string;code:string;sequence:number;curriculum_level_translations:{locale:string;title:string}[]};
type Chapter={id:string;organ_system_id:string;level_id:string;code:string;sequence:number;status:string;chapter_translations:{locale:string;title:string;subtitle:string|null}[]};
type Pool={id:string;organ_system_id:string;chapter_id:string|null;purpose:string;case_pool_translations:{locale:string;title:string}[]};

const tr=(items:any[]|undefined,locale='de')=>items?.find(x=>x.locale===locale)||items?.find(x=>x.locale==='de');

function Login(){
  const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[msg,setMsg]=useState('');
  const submit=async(mode:'login'|'signup')=>{setMsg('');const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setMsg(r.error.message);else if(mode==='signup'&&!r.data.session)setMsg('Account erstellt. Bitte bestätige ggf. die E-Mail.');};
  return <div className="login-shell"><section className="brand-panel"><div className="logo">M</div><h1>Medilingo Authoring</h1><p>Curriculum, Lerninhalte und Clinical Cases strukturiert erstellen, importieren, prüfen und veröffentlichen.</p></section><section className="login-card"><h2>Anmelden</h2><label>E-Mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Passwort<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{msg&&<div className="notice">{msg}</div>}<button className="primary" onClick={()=>submit('login')}>Einloggen</button><button className="secondary" onClick={()=>submit('signup')}>Account anlegen</button></section></div>
}

export default function App(){
  const[session,setSession]=useState<any>(null); const[profile,setProfile]=useState<Profile|null>(null); const[page,setPage]=useState<Page>('dashboard');
  const[organs,setOrgans]=useState<Organ[]>([]); const[levels,setLevels]=useState<Level[]>([]); const[chapters,setChapters]=useState<Chapter[]>([]); const[pools,setPools]=useState<Pool[]>([]); const[cases,setCases]=useState<any[]>([]); const[content,setContent]=useState<any[]>([]); const[uploads,setUploads]=useState<any[]>([]);
  const[msg,setMsg]=useState(''); const[busy,setBusy]=useState(false); const[caseDraft,setCaseDraft]=useState<CaseDraft|null>(null); const[chapterOpen,setChapterOpen]=useState(false); const[contentOpen,setContentOpen]=useState(false);
  const[chapterForm,setChapterForm]=useState<any>({organ:'',level:'',code:'',sequence:1,titleDe:'',subtitleDe:'',titleEn:'',subtitleEn:''});
  const[contentForm,setContentForm]=useState<any>({type:'knowledge',code:'',chapter:'',sequence:1,titleDe:'',bodyDe:'',titleEn:'',bodyEn:'',options:'',answer:'',explanationDe:'',explanationEn:''});

  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
  const load=async()=>{if(!session)return;const[p,o,l,c,po,ca,ci,u]=await Promise.all([
    supabase.from('profiles').select('id,role,display_name').eq('id',session.user.id).single(),
    supabase.from('organ_systems').select('id,code,organ_system_translations(locale,name)').order('sequence'),
    supabase.from('curriculum_levels').select('id,organ_system_id,code,sequence,curriculum_level_translations(locale,title)').order('sequence'),
    supabase.from('chapters').select('id,organ_system_id,level_id,code,sequence,status,chapter_translations(locale,title,subtitle)').order('sequence'),
    supabase.from('case_pools').select('id,organ_system_id,chapter_id,purpose,case_pool_translations(locale,title)'),
    supabase.from('cases').select('id,case_code,scenario_code,difficulty,purpose,status,created_at,case_translations(locale,title)').neq('status','archived').order('created_at',{ascending:false}),
    supabase.from('content_items').select('id,content_code,content_type,status,content_version,created_at,content_translations(locale,payload)').neq('status','archived').order('created_at',{ascending:false}),
    supabase.from('authoring_uploads').select('id,original_filename,mime_type,import_status,detected_type,created_at,error_message').order('created_at',{ascending:false})
  ]);if(p.data)setProfile(p.data as Profile);setOrgans((o.data||[])as any);setLevels((l.data||[])as any);setChapters((c.data||[])as any);setPools((po.data||[])as any);setCases(ca.data||[]);setContent(ci.data||[]);setUploads(u.data||[])};
  useEffect(()=>{load()},[session]);
  const canAuthor=!!profile&&['author','reviewer','publisher','admin'].includes(profile.role);
  const visibleLevels=useMemo(()=>levels.filter(x=>!chapterForm.organ||x.organ_system_id===chapterForm.organ),[levels,chapterForm.organ]);
  const bootstrap=async()=>{setMsg('');const r=await supabase.rpc('bootstrap_first_admin');if(r.error)setMsg(r.error.message);else{setMsg('Admin aktiviert.');await load()}};

  const saveChapter=async()=>{if(busy)return;setBusy(true);setMsg('');try{if(!profile||!canAuthor)throw new Error('Keine Autorenberechtigung.');if(!chapterForm.organ||!chapterForm.level||!chapterForm.code.trim()||!chapterForm.titleDe.trim())throw new Error('Organsystem, Level, Code und deutscher Titel sind Pflicht.');const r=await supabase.from('chapters').insert({organ_system_id:chapterForm.organ,level_id:chapterForm.level,code:chapterForm.code.trim(),sequence:Number(chapterForm.sequence)||1,status:'draft',created_by:profile.id,updated_by:profile.id}).select('id').single();if(r.error)throw r.error;const trs:any[]=[{chapter_id:r.data.id,locale:'de',title:chapterForm.titleDe.trim(),subtitle:chapterForm.subtitleDe.trim()||null,status:'draft'}];if(chapterForm.titleEn.trim())trs.push({chapter_id:r.data.id,locale:'en',title:chapterForm.titleEn.trim(),subtitle:chapterForm.subtitleEn.trim()||null,status:'draft'});const t=await supabase.from('chapter_translations').insert(trs);if(t.error)throw t.error;setMsg('Kapitel als Draft gespeichert.');setChapterOpen(false);await load();}catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};
  const saveContent=async()=>{if(busy)return;setBusy(true);setMsg('');try{if(!profile||!canAuthor)throw new Error('Keine Autorenberechtigung.');if(!contentForm.code.trim()||!contentForm.titleDe.trim())throw new Error('Code und deutscher Titel sind Pflicht.');const config:any={};if(contentForm.options.trim())config.options=contentForm.options.split('\n').map((x:string)=>x.trim()).filter(Boolean);if(contentForm.answer.trim())config.answer=contentForm.answer.trim();const r=await supabase.from('content_items').insert({content_code:contentForm.code.trim(),content_type:contentForm.type,config,status:'draft',created_by:profile.id,updated_by:profile.id}).select('id').single();if(r.error)throw r.error;const trs:any[]=[{content_item_id:r.data.id,locale:'de',payload:{title:contentForm.titleDe.trim(),body:contentForm.bodyDe.trim(),explanation:contentForm.explanationDe.trim()||null},status:'draft'}];if(contentForm.titleEn.trim())trs.push({content_item_id:r.data.id,locale:'en',payload:{title:contentForm.titleEn.trim(),body:contentForm.bodyEn.trim(),explanation:contentForm.explanationEn.trim()||null},status:'draft'});const t=await supabase.from('content_translations').insert(trs);if(t.error)throw t.error;if(contentForm.chapter){const n=await supabase.from('chapter_nodes').insert({chapter_id:contentForm.chapter,sequence:Number(contentForm.sequence)||1,node_type:contentForm.type,content_item_id:r.data.id});if(n.error)throw n.error}setMsg('Lerninhalt als Draft gespeichert.');setContentOpen(false);await load();}catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  if(!session)return <Login/>; if(!profile)return <div className="splash">Medilingo wird geladen…</div>;
  const nav:[Page,string][]=[['dashboard','Dashboard'],['curriculum','Curriculum'],['content','Lerninhalte'],['cases','Clinical Cases'],['uploads','Upload Inbox']];
  return <div className="shell"><aside><div className="brand"><div className="logo small">M</div><div><b>Medilingo</b><span>Content Workbench</span></div></div><nav>{nav.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><div className="account"><span>{session.user.email}</span><b>{profile.role}</b><button onClick={()=>supabase.auth.signOut()}>Logout</button></div></aside><main>{msg&&<div className="notice top-notice">{msg}</div>}
    {page==='dashboard'&&<><header><div><h1>Dashboard</h1><p>Medilingo Content Workbench</p></div></header>{profile.role==='viewer'&&<div className="card setup-card"><h3>Ersteinrichtung</h3><p>Dieser Account ist noch Viewer. Wenn dies der erste Authoring-Account ist, kannst du ihn einmalig zum Admin machen.</p><button className="primary" onClick={bootstrap}>Ersten Admin aktivieren</button></div>}<div className="stats"><div className="card"><span>Kapitel</span><b>{chapters.length}</b></div><div className="card"><span>Lerninhalte</span><b>{content.length}</b></div><div className="card"><span>Clinical Cases</span><b>{cases.length}</b></div><div className="card"><span>Uploads</span><b>{uploads.length}</b></div></div><div className="card"><h3>Content-Pipeline</h3><p>Authoring und Import erzeugen strukturierte Drafts. Erst nach technischer Validierung und fachlichem Review werden Inhalte veröffentlicht.</p><div className="pipeline"><span>Draft</span><b>→</b><span>Validation</span><b>→</b><span>Review</span><b>→</b><span>Approved</span><b>→</b><span>Published</span></div></div></>}
    {page==='curriculum'&&<><header><div><h1>Curriculum</h1><p>Organsystem → Level → Kapitel. Die Reihenfolge bleibt servergesteuert.</p></div><button className="primary" disabled={!canAuthor} onClick={()=>setChapterOpen(true)}>＋ Kapitel</button></header><div className="card"><div className="table"><div className="row head"><span>Kapitel</span><span>Titel</span><span>Status</span><span>Reihenfolge</span></div>{chapters.map(c=><div className="row" key={c.id}><b>{c.code}</b><span>{tr(c.chapter_translations)?.title||'Ohne Titel'}</span><span>{c.status}</span><span>{c.sequence}</span></div>)}</div></div></>}
    {page==='content'&&<><header><div><h1>Lerninhalte</h1><p>Knowledge, Fragen, Flashcards, Free Answer, Checkpoints und Multimedia.</p></div><button className="primary" disabled={!canAuthor} onClick={()=>setContentOpen(true)}>＋ Lerninhalt</button></header><div className="card">{content.length===0?<div className="empty">Noch keine Lerninhalte.</div>:<div className="table"><div className="row head"><span>Code</span><span>Titel</span><span>Typ</span><span>Status</span></div>{content.map(c=><div className="row" key={c.id}><b>{c.content_code}</b><span>{tr(c.content_translations)?.payload?.title||'Ohne Titel'}</span><span>{c.content_type}</span><span>{c.status}</span></div>)}</div>}</div></>}
    {page==='cases'&&<><header><div><h1>Clinical Cases</h1><p>Freie Lernfälle mit Resolver-Aliasen, deterministischen Befunden, Therapieaktionen und Hard Endpoints.</p></div><button className="primary" disabled={!canAuthor} onClick={()=>setCaseDraft(newCaseDraft())}>＋ Neuer Case</button></header><div className="card">{cases.length===0?<div className="empty">Noch keine aktiven Cases.</div>:<div className="table"><div className="row head"><span>Case</span><span>Titel</span><span>Purpose</span><span>Status</span></div>{cases.map(c=><div className="row" key={c.id}><b>{c.case_code}</b><span>{tr(c.case_translations)?.title||c.scenario_code||'Ohne Titel'}</span><span>{c.purpose}</span><span>{c.status}</span></div>)}</div>}</div><div className="callout"><b>Portables Case-Format</b><p>Der neue Builder kann den Fall als strukturiertes JSON exportieren. Dadurch kann ein Case unabhängig vom Authoring-UI weitergegeben, geprüft und später vom iOS Case Engine ausgeführt werden.</p></div></>}
    {page==='uploads'&&<ImportReview uploads={uploads} profileId={profile.id} canAuthor={canAuthor} onRefresh={load} onOpenDraft={d=>setCaseDraft(d)}/>} 
  </main>
  {caseDraft&&<CaseWorkbench profileId={profile.id} organs={organs} chapters={chapters} pools={pools} initialDraft={caseDraft} onSaved={load} onClose={()=>setCaseDraft(null)}/>} 
  {chapterOpen&&<div className="modal-bg"><div className="modal small-modal"><div className="modal-title"><div><h2>Kapitel anlegen</h2><p>Draft; noch nicht veröffentlicht.</p></div><button onClick={()=>setChapterOpen(false)}>×</button></div><div className="grid2"><label>Organsystem<select value={chapterForm.organ} onChange={e=>setChapterForm({...chapterForm,organ:e.target.value,level:''})}><option value="">Auswählen…</option>{organs.map(o=><option key={o.id} value={o.id}>{tr(o.organ_system_translations)?.name||o.code}</option>)}</select></label><label>Level<select value={chapterForm.level} onChange={e=>setChapterForm({...chapterForm,level:e.target.value})}><option value="">Auswählen…</option>{visibleLevels.map(l=><option key={l.id} value={l.id}>{tr(l.curriculum_level_translations)?.title||l.code}</option>)}</select></label></div><div className="grid2"><label>Code<input value={chapterForm.code} onChange={e=>setChapterForm({...chapterForm,code:e.target.value})}/></label><label>Reihenfolge<input type="number" value={chapterForm.sequence} onChange={e=>setChapterForm({...chapterForm,sequence:e.target.value})}/></label></div><div className="split"><div><h3>Deutsch</h3><label>Titel<input value={chapterForm.titleDe} onChange={e=>setChapterForm({...chapterForm,titleDe:e.target.value})}/></label><label>Untertitel<textarea value={chapterForm.subtitleDe} onChange={e=>setChapterForm({...chapterForm,subtitleDe:e.target.value})}/></label></div><div><h3>English</h3><label>Title<input value={chapterForm.titleEn} onChange={e=>setChapterForm({...chapterForm,titleEn:e.target.value})}/></label><label>Subtitle<textarea value={chapterForm.subtitleEn} onChange={e=>setChapterForm({...chapterForm,subtitleEn:e.target.value})}/></label></div></div><div className="actions"><button className="secondary" onClick={()=>setChapterOpen(false)}>Abbrechen</button><button className="primary" disabled={busy} onClick={saveChapter}>Draft speichern</button></div></div></div>}
  {contentOpen&&<div className="modal-bg"><div className="modal"><div className="modal-title"><div><h2>Lerninhalt anlegen</h2><p>Generischer Node-Content für den Curriculum-Pfad.</p></div><button onClick={()=>setContentOpen(false)}>×</button></div><div className="grid3"><label>Typ<select value={contentForm.type} onChange={e=>setContentForm({...contentForm,type:e.target.value})}><option value="knowledge">Knowledge</option><option value="flashcards">Flashcards</option><option value="multiple_choice">Multiple Choice</option><option value="free_answer">Free Answer</option><option value="checkpoint">Checkpoint</option><option value="multimedia">Multimedia</option><option value="milestone">Milestone</option><option value="level_milestone">Level Milestone</option></select></label><label>Content-Code<input value={contentForm.code} onChange={e=>setContentForm({...contentForm,code:e.target.value})}/></label><label>Kapitel<select value={contentForm.chapter} onChange={e=>setContentForm({...contentForm,chapter:e.target.value})}><option value="">Noch nicht zuordnen</option>{chapters.map(c=><option key={c.id} value={c.id}>{tr(c.chapter_translations)?.title||c.code}</option>)}</select></label></div><div className="split"><div><h3>Deutsch</h3><label>Titel<input value={contentForm.titleDe} onChange={e=>setContentForm({...contentForm,titleDe:e.target.value})}/></label><label>Inhalt<textarea value={contentForm.bodyDe} onChange={e=>setContentForm({...contentForm,bodyDe:e.target.value})}/></label><label>Erklärung<textarea value={contentForm.explanationDe} onChange={e=>setContentForm({...contentForm,explanationDe:e.target.value})}/></label></div><div><h3>English</h3><label>Title<input value={contentForm.titleEn} onChange={e=>setContentForm({...contentForm,titleEn:e.target.value})}/></label><label>Content<textarea value={contentForm.bodyEn} onChange={e=>setContentForm({...contentForm,bodyEn:e.target.value})}/></label><label>Explanation<textarea value={contentForm.explanationEn} onChange={e=>setContentForm({...contentForm,explanationEn:e.target.value})}/></label></div></div><div className="grid2"><label>Antwortoptionen · eine pro Zeile<textarea value={contentForm.options} onChange={e=>setContentForm({...contentForm,options:e.target.value})}/></label><label>Korrekte Antwort / Konzept<input value={contentForm.answer} onChange={e=>setContentForm({...contentForm,answer:e.target.value})}/></label></div><div className="actions"><button className="secondary" onClick={()=>setContentOpen(false)}>Abbrechen</button><button className="primary" disabled={busy} onClick={saveContent}>Draft speichern</button></div></div></div>}
  </div>
}
