import { useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';

type Role='viewer'|'author'|'reviewer'|'publisher'|'admin';
type Page='dashboard'|'curriculum'|'content'|'cases'|'uploads';
type Profile={id:string;role:Role;display_name:string|null};
type Organ={id:string;code:string;organ_system_translations:{locale:string;name:string}[]};
type Level={id:string;organ_system_id:string;code:string;sequence:number;curriculum_level_translations:{locale:string;title:string}[]};
type Chapter={id:string;organ_system_id:string;level_id:string;code:string;sequence:number;status:string;chapter_translations:{locale:string;title:string;subtitle:string|null}[]};
type Pool={id:string;organ_system_id:string;chapter_id:string|null;purpose:string;case_pool_translations:{locale:string;title:string}[]};

const tr=(items:any[]|undefined,locale='de')=>items?.find(x=>x.locale===locale)||items?.find(x=>x.locale==='de');
const lines=(value:string)=>value.split('\n').map(x=>x.trim()).filter(Boolean);
const pairs=(value:string)=>lines(value).map(row=>{const [key,...rest]=row.split('|');return {key:key?.trim()||'',value:rest.join('|').trim()}}).filter(x=>x.key||x.value);

function Login(){
  const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[msg,setMsg]=useState('');
  const submit=async(mode:'login'|'signup')=>{setMsg('');const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setMsg(r.error.message);else if(mode==='signup'&&!r.data.session)setMsg('Account erstellt. Bitte bestätige ggf. die E-Mail.');};
  return <div className="login-shell"><section className="brand-panel"><div className="logo">M</div><h1>Medilingo Authoring</h1><p>Curriculum, Lerninhalte und Clinical Cases strukturiert erstellen, prüfen und veröffentlichen.</p></section><section className="login-card"><h2>Anmelden</h2><label>E-Mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Passwort<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{msg&&<div className="notice">{msg}</div>}<button className="primary" onClick={()=>submit('login')}>Einloggen</button><button className="secondary" onClick={()=>submit('signup')}>Account anlegen</button></section></div>
}

const Section=({title,children}:{title:string;children:any})=><section className="editor-section"><h3>{title}</h3>{children}</section>;

export default function App(){
  const[session,setSession]=useState<any>(null); const[profile,setProfile]=useState<Profile|null>(null); const[page,setPage]=useState<Page>('dashboard');
  const[organs,setOrgans]=useState<Organ[]>([]); const[levels,setLevels]=useState<Level[]>([]); const[chapters,setChapters]=useState<Chapter[]>([]); const[pools,setPools]=useState<Pool[]>([]); const[cases,setCases]=useState<any[]>([]); const[content,setContent]=useState<any[]>([]); const[uploads,setUploads]=useState<any[]>([]);
  const[msg,setMsg]=useState(''); const[busy,setBusy]=useState(false); const[caseOpen,setCaseOpen]=useState(false); const[contentOpen,setContentOpen]=useState(false); const[chapterOpen,setChapterOpen]=useState(false);

  const[caseForm,setCaseForm]=useState<any>({organ:'',chapter:'',pool:'',difficulty:2,purpose:'practice',scenario:'',duration:15,titleDe:'',titleEn:'',openingDe:'',openingEn:'',age:'',sex:'',context:'',chiefComplaint:'',historyDe:'',historyEn:'',medications:'',allergies:'',targetDiagnosis:'',differentials:'',pathophysiology:'',criticalFindings:'',historyTopics:'',exams:'',diagnostics:'',treatments:'',diagnosisEndpoints:'',treatmentEndpoints:'',hintsDe:'',hintsEn:'',debriefDe:'',debriefEn:'',objectivesDe:'',objectivesEn:''});
  const[contentForm,setContentForm]=useState<any>({type:'knowledge',code:'',chapter:'',sequence:1,titleDe:'',bodyDe:'',titleEn:'',bodyEn:'',options:'',answer:'',explanationDe:'',explanationEn:''});
  const[chapterForm,setChapterForm]=useState<any>({organ:'',level:'',code:'',sequence:1,titleDe:'',subtitleDe:'',titleEn:'',subtitleEn:''});

  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
  const load=async()=>{if(!session)return;const[p,o,l,c,po,ca,ci,u]=await Promise.all([
    supabase.from('profiles').select('id,role,display_name').eq('id',session.user.id).single(),
    supabase.from('organ_systems').select('id,code,organ_system_translations(locale,name)').order('sequence'),
    supabase.from('curriculum_levels').select('id,organ_system_id,code,sequence,curriculum_level_translations(locale,title)').order('sequence'),
    supabase.from('chapters').select('id,organ_system_id,level_id,code,sequence,status,chapter_translations(locale,title,subtitle)').order('sequence'),
    supabase.from('case_pools').select('id,organ_system_id,chapter_id,purpose,case_pool_translations(locale,title)'),
    supabase.from('cases').select('id,case_code,difficulty,purpose,status,created_at,case_translations(locale,title)').neq('status','archived').order('created_at',{ascending:false}),
    supabase.from('content_items').select('id,content_code,content_type,status,content_version,created_at,content_translations(locale,payload)').neq('status','archived').order('created_at',{ascending:false}),
    supabase.from('authoring_uploads').select('id,original_filename,mime_type,import_status,detected_type,created_at').order('created_at',{ascending:false})
  ]);if(p.data)setProfile(p.data as Profile);setOrgans((o.data||[])as any);setLevels((l.data||[])as any);setChapters((c.data||[])as any);setPools((po.data||[])as any);setCases(ca.data||[]);setContent(ci.data||[]);setUploads(u.data||[])};
  useEffect(()=>{load()},[session]);
  const canAuthor=!!profile&&['author','reviewer','publisher','admin'].includes(profile.role);
  const visibleLevels=useMemo(()=>levels.filter(x=>!chapterForm.organ||x.organ_system_id===chapterForm.organ),[levels,chapterForm.organ]);
  const caseChapters=useMemo(()=>chapters.filter(x=>!caseForm.organ||x.organ_system_id===caseForm.organ),[chapters,caseForm.organ]);
  const casePools=useMemo(()=>pools.filter(x=>(!caseForm.organ||x.organ_system_id===caseForm.organ)&&(!caseForm.chapter||!x.chapter_id||x.chapter_id===caseForm.chapter)),[pools,caseForm.organ,caseForm.chapter]);

  const bootstrap=async()=>{setMsg('');const r=await supabase.rpc('bootstrap_first_admin');if(r.error)setMsg(r.error.message);else{setMsg('Admin aktiviert.');await load()}};

  const saveCase=async()=>{if(busy)return;setBusy(true);setMsg('');try{
    if(!profile||!canAuthor)throw new Error('Keine Autorenberechtigung.'); if(!caseForm.organ)throw new Error('Organsystem fehlt.'); if(!caseForm.titleDe.trim())throw new Error('Deutscher Titel fehlt.');
    const medical_logic={
      demographics:{age:caseForm.age||null,sex:caseForm.sex||null,context:caseForm.context||null},
      chief_complaint:caseForm.chiefComplaint||null,
      target_diagnosis_id:caseForm.targetDiagnosis.trim()||null,
      differential_diagnoses:lines(caseForm.differentials),pathophysiology:caseForm.pathophysiology||null,critical_findings:lines(caseForm.criticalFindings),
      medications:lines(caseForm.medications),allergies:lines(caseForm.allergies),
      history_topics:pairs(caseForm.historyTopics).map(x=>({topic_id:x.key,expected_response:x.value})),
      examinations:pairs(caseForm.exams).map(x=>({exam_id:x.key,finding:x.value})),
      diagnostics:lines(caseForm.diagnostics).map(row=>{const[a,b,c,d]=row.split('|').map((x:string)=>x.trim());return{action_id:a||'',result:b||'',delay_seconds:Number(c)||0,relevance:d||''}}),
      treatments:lines(caseForm.treatments).map(row=>{const[a,b,c]=row.split('|').map((x:string)=>x.trim());return{action_id:a||'',effect:b||'',required:(c||'').toLowerCase()==='required'}}),
      hard_endpoints:{diagnosis:lines(caseForm.diagnosisEndpoints),treatment:lines(caseForm.treatmentEndpoints)},estimated_minutes:Number(caseForm.duration)||null
    };
    const cr=await supabase.from('cases').insert({organ_system_id:caseForm.organ,chapter_id:caseForm.chapter||null,scenario_code:caseForm.scenario.trim()||null,difficulty:Number(caseForm.difficulty),purpose:caseForm.purpose,status:'draft',medical_logic,created_by:profile.id,updated_by:profile.id}).select('id,case_code').single();if(cr.error)throw cr.error;
    const localized=(locale:string,title:string,opening:string,history:string,hints:string,debrief:string,objectives:string)=>({case_id:cr.data.id,locale,title:title.trim(),patient_presentation:opening.trim()||null,payload:{history_summary:history.trim()||null,hints:lines(hints),debrief:debrief.trim()||null,learning_objectives:lines(objectives)},status:'draft'});
    const trs=[localized('de',caseForm.titleDe,caseForm.openingDe,caseForm.historyDe,caseForm.hintsDe,caseForm.debriefDe,caseForm.objectivesDe)]; if(caseForm.titleEn.trim())trs.push(localized('en',caseForm.titleEn,caseForm.openingEn,caseForm.historyEn,caseForm.hintsEn,caseForm.debriefEn,caseForm.objectivesEn));
    const trr=await supabase.from('case_translations').insert(trs);if(trr.error)throw trr.error;if(caseForm.pool){const pr=await supabase.from('case_pool_members').insert({case_pool_id:caseForm.pool,case_id:cr.data.id});if(pr.error)throw pr.error}
    setMsg(`Case gespeichert: ${cr.data.case_code}`);setCaseOpen(false);await load();
  }catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  const saveContent=async()=>{if(busy)return;setBusy(true);setMsg('');try{if(!profile||!canAuthor)throw new Error('Keine Autorenberechtigung.');if(!contentForm.code.trim())throw new Error('Content-Code fehlt.');if(!contentForm.titleDe.trim())throw new Error('Deutscher Titel fehlt.');
    const config:any={}; if(contentForm.type==='multiple_choice'||contentForm.type==='checkpoint')config.answer=contentForm.answer.trim()||null; if(contentForm.options.trim())config.options=lines(contentForm.options);
    const r=await supabase.from('content_items').insert({content_code:contentForm.code.trim(),content_type:contentForm.type,config,status:'draft',created_by:profile.id,updated_by:profile.id}).select('id').single();if(r.error)throw r.error;
    const translations:any[]=[{content_item_id:r.data.id,locale:'de',payload:{title:contentForm.titleDe.trim(),body:contentForm.bodyDe.trim(),explanation:contentForm.explanationDe.trim()||null},status:'draft'}];if(contentForm.titleEn.trim())translations.push({content_item_id:r.data.id,locale:'en',payload:{title:contentForm.titleEn.trim(),body:contentForm.bodyEn.trim(),explanation:contentForm.explanationEn.trim()||null},status:'draft'});const t=await supabase.from('content_translations').insert(translations);if(t.error)throw t.error;
    if(contentForm.chapter){const n=await supabase.from('chapter_nodes').insert({chapter_id:contentForm.chapter,sequence:Number(contentForm.sequence)||1,node_type:contentForm.type,content_item_id:r.data.id});if(n.error)throw n.error}
    setMsg('Lerninhalt als Draft gespeichert.');setContentOpen(false);await load();
  }catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  const saveChapter=async()=>{if(busy)return;setBusy(true);setMsg('');try{if(!profile||!canAuthor)throw new Error('Keine Autorenberechtigung.');if(!chapterForm.organ||!chapterForm.level||!chapterForm.code.trim()||!chapterForm.titleDe.trim())throw new Error('Organsystem, Level, Code und deutscher Titel sind Pflicht.');const r=await supabase.from('chapters').insert({organ_system_id:chapterForm.organ,level_id:chapterForm.level,code:chapterForm.code.trim(),sequence:Number(chapterForm.sequence)||1,status:'draft',created_by:profile.id,updated_by:profile.id}).select('id').single();if(r.error)throw r.error;const trs:any[]=[{chapter_id:r.data.id,locale:'de',title:chapterForm.titleDe.trim(),subtitle:chapterForm.subtitleDe.trim()||null,status:'draft'}];if(chapterForm.titleEn.trim())trs.push({chapter_id:r.data.id,locale:'en',title:chapterForm.titleEn.trim(),subtitle:chapterForm.subtitleEn.trim()||null,status:'draft'});const t=await supabase.from('chapter_translations').insert(trs);if(t.error)throw t.error;setMsg('Kapitel als Draft gespeichert.');setChapterOpen(false);await load();}catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  const uploadFile=async(e:any)=>{const file=e.target.files?.[0];if(!file||!profile)return;setBusy(true);setMsg('');try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${profile.id}/${Date.now()}-${safe}`;const u=await supabase.storage.from('authoring-uploads').upload(path,file,{contentType:file.type||undefined,upsert:false});if(u.error)throw u.error;const detected=file.name.toLowerCase().endsWith('.docx')?'docx':file.name.toLowerCase().endsWith('.xlsx')||file.name.toLowerCase().endsWith('.xls')?'spreadsheet':file.name.toLowerCase().endsWith('.pdf')?'pdf':'document';const r=await supabase.from('authoring_uploads').insert({uploaded_by:profile.id,original_filename:file.name,storage_path:path,mime_type:file.type||null,detected_type:detected,import_status:'uploaded'});if(r.error)throw r.error;setMsg('Datei hochgeladen. Sie liegt jetzt in der Import-Inbox.');await load()}catch(err:any){setMsg(err.message||String(err))}finally{setBusy(false);e.target.value=''}};

  if(!session)return <Login/>; if(!profile)return <div className="splash">Medilingo wird geladen…</div>;
  const activeCases=cases.length; const draftContent=content.length;
  return <div className="shell"><aside><div className="brand"><div className="logo small">M</div><div><b>Medilingo</b><span>Content Workbench</span></div></div><nav>{([['dashboard','Dashboard'],['curriculum','Curriculum'],['content','Lerninhalte'],['cases','Clinical Cases'],['uploads','Upload Inbox']] as [Page,string][]).map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><div className="account"><span>{session.user.email}</span><b>{profile.role}</b><button onClick={()=>supabase.auth.signOut()}>Logout</button></div></aside><main>
    {msg&&<div className="notice top-notice">{msg}</div>}
    {page==='dashboard'&&<><header><div><h1>Dashboard</h1><p>Medilingo Content Workbench</p></div></header>{profile.role==='viewer'&&<div className="card setup-card"><h3>Ersteinrichtung</h3><p>Dieser Account ist noch Viewer. Wenn dies der erste Authoring-Account ist, kannst du ihn einmalig zum Admin machen.</p><button className="primary" onClick={bootstrap}>Ersten Admin aktivieren</button></div>}<div className="stats"><div className="card"><span>Kapitel</span><b>{chapters.length}</b></div><div className="card"><span>Lerninhalte</span><b>{draftContent}</b></div><div className="card"><span>Clinical Cases</span><b>{activeCases}</b></div><div className="card"><span>Uploads</span><b>{uploads.length}</b></div></div><div className="card"><h3>Workflow</h3><p>Draft → Validation → Review → Approved → Published</p><p className="muted">Autoren erfassen Inhalte strukturiert; die App lädt später ausschließlich freigegebene Releases.</p></div></>}
    {page==='curriculum'&&<><header><div><h1>Curriculum</h1><p>Organsysteme, Level und Kapitel.</p></div><button className="primary" disabled={!canAuthor} onClick={()=>setChapterOpen(true)}>+ Kapitel</button></header><div className="card"><div className="table"><div className="row head"><span>Code</span><span>Titel</span><span>Level</span><span>Status</span></div>{chapters.map(c=><div className="row" key={c.id}><b>{c.code}</b><span>{tr(c.chapter_translations)?.title||'—'}</span><span>{tr(levels.find(l=>l.id===c.level_id)?.curriculum_level_translations)?.title||'—'}</span><span>{c.status}</span></div>)}</div></div></>}
    {page==='content'&&<><header><div><h1>Lerninhalte</h1><p>Knowledge, Flashcards, MC, Free Answer und Checkpoints.</p></div><button className="primary" disabled={!canAuthor} onClick={()=>setContentOpen(true)}>+ Lerninhalt</button></header><div className="card">{content.length===0?<div className="empty">Noch keine Lerninhalte angelegt.</div>:<div className="table"><div className="row head"><span>Code</span><span>Titel</span><span>Typ</span><span>Status</span></div>{content.map(c=><div className="row" key={c.id}><b>{c.content_code}</b><span>{tr(c.content_translations)?.payload?.title||'—'}</span><span>{c.content_type}</span><span>{c.status}</span></div>)}</div>}</div></>}
    {page==='cases'&&<><header><div><h1>Clinical Cases</h1><p>Strukturierte Falllogik, Lokalisierung, Diagnostik, Therapie und Endpunkte.</p></div><button className="primary" disabled={!canAuthor} onClick={()=>setCaseOpen(true)}>+ Neuer Case</button></header><div className="card">{cases.length===0?<div className="empty">Keine aktiven Cases. Die beiden Testfälle wurden archiviert.</div>:<div className="table"><div className="row head"><span>Case</span><span>Titel</span><span>Purpose</span><span>Status</span></div>{cases.map(c=><div className="row" key={c.id}><b>{c.case_code}</b><span>{tr(c.case_translations)?.title||'—'}</span><span>{c.purpose}</span><span>{c.status}</span></div>)}</div>}</div></>}
    {page==='uploads'&&<><header><div><h1>Upload Inbox</h1><p>DOCX, XLSX, PDF und andere Quelldateien als Authoring-Input.</p></div><label className={'primary upload-btn '+(busy?'disabled':'')}>Datei hochladen<input type="file" accept=".doc,.docx,.xls,.xlsx,.pdf,.txt,.csv" disabled={busy} onChange={uploadFile}/></label></header><div className="card"><div className="upload-help"><b>Import-Workflow</b><span>Upload → Parser → Validierung → Review → Draft übernehmen</span></div>{uploads.length===0?<div className="empty">Noch keine Dateien in der Inbox.</div>:<div className="table"><div className="row head"><span>Datei</span><span>Typ</span><span>Status</span><span>Datum</span></div>{uploads.map(u=><div className="row" key={u.id}><b>{u.original_filename}</b><span>{u.detected_type||u.mime_type||'—'}</span><span>{u.import_status}</span><span>{new Date(u.created_at).toLocaleString('de-DE')}</span></div>)}</div>}</div></>}
  </main>

  {chapterOpen&&<div className="modal-bg"><div className="modal"><div className="modal-title"><div><h2>Kapitel anlegen</h2><p>Struktur wird serverseitig gespeichert und später im Manifest ausgeliefert.</p></div><button onClick={()=>setChapterOpen(false)}>×</button></div><div className="grid3"><label>Organsystem<select value={chapterForm.organ} onChange={e=>setChapterForm({...chapterForm,organ:e.target.value,level:''})}><option value="">Auswählen…</option>{organs.map(o=><option key={o.id} value={o.id}>{tr(o.organ_system_translations)?.name||o.code}</option>)}</select></label><label>Level<select value={chapterForm.level} onChange={e=>setChapterForm({...chapterForm,level:e.target.value})}><option value="">Auswählen…</option>{visibleLevels.map(l=><option key={l.id} value={l.id}>{tr(l.curriculum_level_translations)?.title||l.code}</option>)}</select></label><label>Sequenz<input type="number" min="1" value={chapterForm.sequence} onChange={e=>setChapterForm({...chapterForm,sequence:e.target.value})}/></label></div><label>Stabiler Code<input value={chapterForm.code} onChange={e=>setChapterForm({...chapterForm,code:e.target.value})} placeholder="cardio_heart_anatomy"/></label><div className="split"><Section title="Deutsch"><label>Titel<input value={chapterForm.titleDe} onChange={e=>setChapterForm({...chapterForm,titleDe:e.target.value})}/></label><label>Untertitel<textarea value={chapterForm.subtitleDe} onChange={e=>setChapterForm({...chapterForm,subtitleDe:e.target.value})}/></label></Section><Section title="English"><label>Title<input value={chapterForm.titleEn} onChange={e=>setChapterForm({...chapterForm,titleEn:e.target.value})}/></label><label>Subtitle<textarea value={chapterForm.subtitleEn} onChange={e=>setChapterForm({...chapterForm,subtitleEn:e.target.value})}/></label></Section></div><div className="actions"><button className="secondary" onClick={()=>setChapterOpen(false)}>Abbrechen</button><button className="primary" disabled={busy} onClick={saveChapter}>{busy?'Speichert…':'Als Draft speichern'}</button></div></div></div>}

  {contentOpen&&<div className="modal-bg"><div className="modal"><div className="modal-title"><div><h2>Lerninhalt anlegen</h2><p>Generischer Editor für die bekannten Node-Typen.</p></div><button onClick={()=>setContentOpen(false)}>×</button></div><div className="grid3"><label>Typ<select value={contentForm.type} onChange={e=>setContentForm({...contentForm,type:e.target.value})}>{['knowledge','flashcards','multiple_choice','free_answer','checkpoint','multimedia','milestone','level_milestone'].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Content-Code<input value={contentForm.code} onChange={e=>setContentForm({...contentForm,code:e.target.value})} placeholder="cardio_anatomy_001"/></label><label>Sequenz<input type="number" min="1" value={contentForm.sequence} onChange={e=>setContentForm({...contentForm,sequence:e.target.value})}/></label></div><label>Kapitel<select value={contentForm.chapter} onChange={e=>setContentForm({...contentForm,chapter:e.target.value})}><option value="">Noch keinem Kapitel zuordnen</option>{chapters.map(c=><option key={c.id} value={c.id}>{tr(c.chapter_translations)?.title||c.code}</option>)}</select></label><div className="split"><Section title="Deutsch"><label>Titel<input value={contentForm.titleDe} onChange={e=>setContentForm({...contentForm,titleDe:e.target.value})}/></label><label>Inhalt / Prompt<textarea className="tall" value={contentForm.bodyDe} onChange={e=>setContentForm({...contentForm,bodyDe:e.target.value})}/></label><label>Erklärung<textarea value={contentForm.explanationDe} onChange={e=>setContentForm({...contentForm,explanationDe:e.target.value})}/></label></Section><Section title="English"><label>Title<input value={contentForm.titleEn} onChange={e=>setContentForm({...contentForm,titleEn:e.target.value})}/></label><label>Content / Prompt<textarea className="tall" value={contentForm.bodyEn} onChange={e=>setContentForm({...contentForm,bodyEn:e.target.value})}/></label><label>Explanation<textarea value={contentForm.explanationEn} onChange={e=>setContentForm({...contentForm,explanationEn:e.target.value})}/></label></Section></div>{['multiple_choice','checkpoint','flashcards'].includes(contentForm.type)&&<Section title="Antwortlogik"><label>Optionen / Karten – eine Zeile pro Eintrag<textarea value={contentForm.options} onChange={e=>setContentForm({...contentForm,options:e.target.value})}/></label><label>Korrekte Antwort / Lösung<input value={contentForm.answer} onChange={e=>setContentForm({...contentForm,answer:e.target.value})}/></label></Section>}<div className="actions"><button className="secondary" onClick={()=>setContentOpen(false)}>Abbrechen</button><button className="primary" disabled={busy} onClick={saveContent}>{busy?'Speichert…':'Als Draft speichern'}</button></div></div></div>}

  {caseOpen&&<div className="modal-bg"><div className="modal case-modal"><div className="modal-title"><div><h2>Clinical Case Builder</h2><p>Medizinische Logik sprachneutral, Patiententexte DE/EN getrennt.</p></div><button onClick={()=>setCaseOpen(false)}>×</button></div>
    <Section title="1 · Einordnung"><div className="grid3"><label>Organsystem<select value={caseForm.organ} onChange={e=>setCaseForm({...caseForm,organ:e.target.value,chapter:'',pool:''})}><option value="">Auswählen…</option>{organs.map(o=><option key={o.id} value={o.id}>{tr(o.organ_system_translations)?.name||o.code}</option>)}</select></label><label>Kapitel<select value={caseForm.chapter} onChange={e=>setCaseForm({...caseForm,chapter:e.target.value,pool:''})}><option value="">Kein Kapitel</option>{caseChapters.map(c=><option key={c.id} value={c.id}>{tr(c.chapter_translations)?.title||c.code}</option>)}</select></label><label>Case Pool<select value={caseForm.pool} onChange={e=>setCaseForm({...caseForm,pool:e.target.value})}><option value="">Später zuordnen</option>{casePools.map(p=><option key={p.id} value={p.id}>{tr(p.case_pool_translations)?.title||'Pool'}</option>)}</select></label></div><div className="grid3"><label>Purpose<select value={caseForm.purpose} onChange={e=>setCaseForm({...caseForm,purpose:e.target.value})}><option value="practice">Practice</option><option value="curriculum_gate">Curriculum Gate</option><option value="weekly_challenge">Weekly Challenge</option></select></label><label>Schwierigkeit<select value={caseForm.difficulty} onChange={e=>setCaseForm({...caseForm,difficulty:e.target.value})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Dauer (Min.)<input type="number" min="1" value={caseForm.duration} onChange={e=>setCaseForm({...caseForm,duration:e.target.value})}/></label></div><label>Scenario-Code<input value={caseForm.scenario} onChange={e=>setCaseForm({...caseForm,scenario:e.target.value})} placeholder="acute_chest_pain"/></label></Section>
    <Section title="2 · Patient"><div className="grid3"><label>Alter<input value={caseForm.age} onChange={e=>setCaseForm({...caseForm,age:e.target.value})} placeholder="67"/></label><label>Geschlecht / Sex<input value={caseForm.sex} onChange={e=>setCaseForm({...caseForm,sex:e.target.value})} placeholder="male"/></label><label>Kontext<input value={caseForm.context} onChange={e=>setCaseForm({...caseForm,context:e.target.value})} placeholder="ED / Hausarzt / Station"/></label></div><label>Chief Complaint · sprachneutral<input value={caseForm.chiefComplaint} onChange={e=>setCaseForm({...caseForm,chiefComplaint:e.target.value})}/></label><div className="split"><div><label>Titel DE<input value={caseForm.titleDe} onChange={e=>setCaseForm({...caseForm,titleDe:e.target.value})}/></label><label>Eröffnung / Patientenvorstellung DE<textarea value={caseForm.openingDe} onChange={e=>setCaseForm({...caseForm,openingDe:e.target.value})}/></label><label>Anamnese-Zusammenfassung DE<textarea value={caseForm.historyDe} onChange={e=>setCaseForm({...caseForm,historyDe:e.target.value})}/></label></div><div><label>Title EN<input value={caseForm.titleEn} onChange={e=>setCaseForm({...caseForm,titleEn:e.target.value})}/></label><label>Opening / Patient presentation EN<textarea value={caseForm.openingEn} onChange={e=>setCaseForm({...caseForm,openingEn:e.target.value})}/></label><label>History summary EN<textarea value={caseForm.historyEn} onChange={e=>setCaseForm({...caseForm,historyEn:e.target.value})}/></label></div></div><div className="grid2"><label>Medikamente · eine Zeile pro Eintrag<textarea value={caseForm.medications} onChange={e=>setCaseForm({...caseForm,medications:e.target.value})}/></label><label>Allergien · eine Zeile pro Eintrag<textarea value={caseForm.allergies} onChange={e=>setCaseForm({...caseForm,allergies:e.target.value})}/></label></div></Section>
    <Section title="3 · Hidden Truth"><label>Zieldiagnose-ID<input value={caseForm.targetDiagnosis} onChange={e=>setCaseForm({...caseForm,targetDiagnosis:e.target.value})} placeholder="stemi"/></label><div className="grid2"><label>Differenzialdiagnosen · eine pro Zeile<textarea value={caseForm.differentials} onChange={e=>setCaseForm({...caseForm,differentials:e.target.value})}/></label><label>Kritische Befunde · eine pro Zeile<textarea value={caseForm.criticalFindings} onChange={e=>setCaseForm({...caseForm,criticalFindings:e.target.value})}/></label></div><label>Pathophysiologie<textarea value={caseForm.pathophysiology} onChange={e=>setCaseForm({...caseForm,pathophysiology:e.target.value})}/></label></Section>
    <Section title="4 · Gespräch & Untersuchung"><label>Anamnese-Topics · Format: topic_id | erwartete Antwort<textarea className="tall" value={caseForm.historyTopics} onChange={e=>setCaseForm({...caseForm,historyTopics:e.target.value})} placeholder={'pain_onset | Seit 45 Minuten plötzlich begonnen\nrisk_factors | Raucher, Hypertonie'}/></label><label>Untersuchungen · Format: exam_id | Befund<textarea className="tall" value={caseForm.exams} onChange={e=>setCaseForm({...caseForm,exams:e.target.value})} placeholder={'blood_pressure | 95/60 mmHg\nheart_exam | regelmäßige Tachykardie'}/></label></Section>
    <Section title="5 · Diagnostik"><label>Eine Zeile je Test · action_id | Ergebnis | Delay Sekunden | Relevanz<textarea className="tall" value={caseForm.diagnostics} onChange={e=>setCaseForm({...caseForm,diagnostics:e.target.value})} placeholder={'ecg | ST-Hebungen II III aVF | 5 | critical\ntroponin | 186 ng/L | 20 | supportive'}/></label></Section>
    <Section title="6 · Therapie"><label>Eine Zeile je Maßnahme · action_id | Effekt | required/optional<textarea className="tall" value={caseForm.treatments} onChange={e=>setCaseForm({...caseForm,treatments:e.target.value})} placeholder={'aspirin | Thrombozytenhemmung | required\nreperfusion | Definitive Reperfusion | required'}/></label></Section>
    <Section title="7 · Hard Endpoints"><div className="grid2"><label>Diagnose-Endpunkte · eine ID pro Zeile<textarea value={caseForm.diagnosisEndpoints} onChange={e=>setCaseForm({...caseForm,diagnosisEndpoints:e.target.value})}/></label><label>Therapie-Endpunkte · eine ID pro Zeile<textarea value={caseForm.treatmentEndpoints} onChange={e=>setCaseForm({...caseForm,treatmentEndpoints:e.target.value})}/></label></div></Section>
    <Section title="8 · Hints, Debrief & Lernziele"><div className="split"><div><label>Hints DE · eine Zeile pro Hint<textarea value={caseForm.hintsDe} onChange={e=>setCaseForm({...caseForm,hintsDe:e.target.value})}/></label><label>Debrief DE<textarea value={caseForm.debriefDe} onChange={e=>setCaseForm({...caseForm,debriefDe:e.target.value})}/></label><label>Lernziele DE · eine Zeile pro Ziel<textarea value={caseForm.objectivesDe} onChange={e=>setCaseForm({...caseForm,objectivesDe:e.target.value})}/></label></div><div><label>Hints EN<textarea value={caseForm.hintsEn} onChange={e=>setCaseForm({...caseForm,hintsEn:e.target.value})}/></label><label>Debrief EN<textarea value={caseForm.debriefEn} onChange={e=>setCaseForm({...caseForm,debriefEn:e.target.value})}/></label><label>Learning objectives EN<textarea value={caseForm.objectivesEn} onChange={e=>setCaseForm({...caseForm,objectivesEn:e.target.value})}/></label></div></div></Section>
    <div className="actions sticky-actions"><button className="secondary" onClick={()=>setCaseOpen(false)}>Abbrechen</button><button className="primary" disabled={busy} onClick={saveCase}>{busy?'Speichert…':'Case als Draft speichern'}</button></div>
  </div></div>}
  </div>
}
