import { useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import { CaseDraft, DiagnosticRow, EndpointRow, ExamRow, HistoryRow, TreatmentRow, VitalRow, DifferentialRow, emptyDiagnostic, emptyEndpoint, emptyExam, emptyHistory, emptyTreatment, emptyVital, emptyDifferential, newCaseDraft, validateCaseDraft } from './caseTypes';

type Organ={id:string;code:string;organ_system_translations:{locale:string;name:string}[]};
type Chapter={id:string;organ_system_id:string;code:string;chapter_translations:{locale:string;title:string}[]};
type Pool={id:string;organ_system_id:string;chapter_id:string|null;case_pool_translations:{locale:string;title:string}[]};
type Props={profileId:string;organs:Organ[];chapters:Chapter[];pools:Pool[];initialDraft?:CaseDraft|null;onSaved:()=>void;onClose:()=>void};

const de=(arr:any[])=>arr?.find(x=>x.locale==='de')?.name||arr?.find(x=>x.locale==='de')?.title||'';
const splitAliases=(v:string)=>v.split('|').map(x=>x.trim()).filter(Boolean);
const splitLines=(v:string)=>v.split('\n').map(x=>x.trim()).filter(Boolean);
const relevance=<><option value="critical">critical</option><option value="important">important</option><option value="supportive">supportive</option><option value="optional">optional</option></>;

function RowActions({onAdd,onDelete}:{onAdd:()=>void;onDelete:()=>void}){return <div className="row-actions"><button type="button" className="mini" onClick={onAdd}>＋</button><button type="button" className="mini danger" onClick={onDelete}>−</button></div>}
function EditorSection({title,subtitle,children}:{title:string;subtitle?:string;children:any}){return <section className="editor-section"><div className="section-heading"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section>}
function Field({label,children}:{label:string;children:any}){return <label><span>{label}</span>{children}</label>}

export default function CaseWorkbench({profileId,organs,chapters,pools,initialDraft,onSaved,onClose}:Props){
  const[d,setD]=useState<CaseDraft>(initialDraft||newCaseDraft()); const[busy,setBusy]=useState(false); const[msg,setMsg]=useState(''); const[tab,setTab]=useState<'builder'|'preview'|'quality'>('builder');
  const visibleChapters=useMemo(()=>chapters.filter(x=>!d.organ||x.organ_system_id===d.organ),[chapters,d.organ]);
  const visiblePools=useMemo(()=>pools.filter(x=>(!d.organ||x.organ_system_id===d.organ)&&(!d.chapter||!x.chapter_id||x.chapter_id===d.chapter)),[pools,d.organ,d.chapter]);
  const quality=validateCaseDraft(d);
  const set=<K extends keyof CaseDraft>(k:K,v:CaseDraft[K])=>setD(x=>({...x,[k]:v}));
  const updateRow=<T,>(key:keyof CaseDraft,index:number,patch:Partial<T>)=>setD(x=>({...x,[key]:(x[key] as T[]).map((r,i)=>i===index?{...r,...patch}:r)}));
  const addRow=<T,>(key:keyof CaseDraft,after:number,row:T)=>setD(x=>{const a=[...x[key] as T[]];a.splice(after+1,0,row);return {...x,[key]:a}});
  const delRow=(key:keyof CaseDraft,index:number)=>setD(x=>({...x,[key]:(x[key] as any[]).filter((_,i)=>i!==index)}));

  const portablePackage=()=>({schema_version:'1.0',document_type:'clinical_case',meta:{scenario_code:d.scenario,purpose:d.purpose,difficulty:d.difficulty,estimated_duration_minutes:d.duration,medical_region:d.medical_region},demographics:{age_years:d.age,sex:d.sex,setting:d.setting,arrival_mode:d.arrival_mode,chief_complaint_de:d.chief_complaint_de,chief_complaint_en:d.chief_complaint_en},localized:{de:{title:d.title_de,patient_presentation:d.presentation_de,hints:splitLines(d.hints_de),debrief:d.debrief_de,learning_objectives:splitLines(d.learning_objectives_de)},en:{title:d.title_en,patient_presentation:d.presentation_en,hints:splitLines(d.hints_en),debrief:d.debrief_en,learning_objectives:splitLines(d.learning_objectives_en)}},medical_logic:{target_diagnosis_id:d.target_diagnosis_id,target_diagnosis_label_de:d.target_diagnosis_label_de,target_diagnosis_label_en:d.target_diagnosis_label_en,pathophysiology_de:d.pathophysiology_de,pathophysiology_en:d.pathophysiology_en,endpoint_policy:d.endpoint_policy,case_truth_note:d.case_truth_note,background:splitLines(d.background),medications:splitLines(d.medications),allergies:splitLines(d.allergies),history_topics:d.history_topics,examinations:d.examinations,vitals:d.vitals,diagnostics:d.diagnostics,differential_diagnoses:d.differential_diagnoses,treatments:d.treatments,hard_endpoints:d.hard_endpoints},author_notes:d.author_notes});
  const exportJson=()=>{const blob=new Blob([JSON.stringify(portablePackage(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${d.scenario||'medilingo-case'}.json`;a.click();URL.revokeObjectURL(a.href)};

  const save=async()=>{if(busy)return;setMsg('');const q=validateCaseDraft(d);if(!q.ok){setTab('quality');setMsg('Bitte zuerst die Pflichtfehler beheben.');return}setBusy(true);try{
    const medical_logic={schema_version:'1.0',demographics:{age_years:d.age?Number(d.age):null,sex:d.sex||null,setting:d.setting||null,arrival_mode:d.arrival_mode||null},chief_complaint:{de:d.chief_complaint_de||null,en:d.chief_complaint_en||null},target_diagnosis_id:d.target_diagnosis_id,target_diagnosis_labels:{de:d.target_diagnosis_label_de||null,en:d.target_diagnosis_label_en||null},pathophysiology:{de:d.pathophysiology_de||null,en:d.pathophysiology_en||null},endpoint_policy:d.endpoint_policy,case_truth_note:d.case_truth_note||null,background:splitLines(d.background),medications:splitLines(d.medications),allergies:splitLines(d.allergies),history_topics:d.history_topics.filter(x=>x.topic_id.trim()).map(x=>({topic_id:x.topic_id,aliases:{de:splitAliases(x.aliases_de),en:splitAliases(x.aliases_en)},relevance:x.relevance})),examinations:d.examinations.filter(x=>x.exam_id.trim()).map(x=>({exam_id:x.exam_id,aliases:{de:splitAliases(x.aliases_de),en:splitAliases(x.aliases_en)},relevance:x.relevance})),vitals:d.vitals.filter(x=>x.measurement_id.trim()),diagnostics:d.diagnostics.filter(x=>x.diagnostic_id.trim()).map(x=>({diagnostic_id:x.diagnostic_id,aliases:{de:splitAliases(x.aliases_de),en:splitAliases(x.aliases_en)},delay_sec:Number(x.delay_sec)||0,relevance:x.relevance})),differential_diagnoses:d.differential_diagnoses.filter(x=>x.diagnosis_id.trim()).map(x=>({diagnosis_id:x.diagnosis_id,priority:x.priority})),treatments:d.treatments.filter(x=>x.action_id.trim()).map(x=>({action_id:x.action_id,aliases:{de:splitAliases(x.aliases_de),en:splitAliases(x.aliases_en)},required:x.required,notes:x.notes||null})),hard_endpoints:d.hard_endpoints.filter(x=>x.endpoint_id.trim()).map(x=>({endpoint_id:x.endpoint_id,category:x.category,required:x.required})),estimated_minutes:d.duration,medical_region:d.medical_region,author_notes:d.author_notes||null,source_upload_id:d.source_upload_id||null};
    const cr=await supabase.from('cases').insert({organ_system_id:d.organ,chapter_id:d.chapter||null,scenario_code:d.scenario,difficulty:Number(d.difficulty),purpose:d.purpose,status:'draft',medical_logic,created_by:profileId,updated_by:profileId}).select('id,case_code').single();if(cr.error)throw cr.error;
    const payload=(locale:'de'|'en')=>({history_responses:Object.fromEntries(d.history_topics.filter(x=>x.topic_id).map(x=>[x.topic_id,locale==='de'?x.response_de:x.response_en])),examination_findings:Object.fromEntries(d.examinations.filter(x=>x.exam_id).map(x=>[x.exam_id,locale==='de'?x.finding_de:x.finding_en])),diagnostic_results:Object.fromEntries(d.diagnostics.filter(x=>x.diagnostic_id).map(x=>[x.diagnostic_id,locale==='de'?x.result_de:x.result_en])),treatment_effects:Object.fromEntries(d.treatments.filter(x=>x.action_id).map(x=>[x.action_id,locale==='de'?x.effect_de:x.effect_en])),differential_labels:Object.fromEntries(d.differential_diagnoses.filter(x=>x.diagnosis_id).map(x=>[x.diagnosis_id,locale==='de'?x.label_de:x.label_en])),endpoint_descriptions:Object.fromEntries(d.hard_endpoints.filter(x=>x.endpoint_id).map(x=>[x.endpoint_id,locale==='de'?x.description_de:x.description_en])),hints:splitLines(locale==='de'?d.hints_de:d.hints_en),debrief:locale==='de'?d.debrief_de:d.debrief_en,learning_objectives:splitLines(locale==='de'?d.learning_objectives_de:d.learning_objectives_en)});
    const trs:any[]=[{case_id:cr.data.id,locale:'de',title:d.title_de,patient_presentation:d.presentation_de,payload:payload('de'),status:'draft'}];if(d.title_en.trim())trs.push({case_id:cr.data.id,locale:'en',title:d.title_en,patient_presentation:d.presentation_en||null,payload:payload('en'),status:'draft'});const trr=await supabase.from('case_translations').insert(trs);if(trr.error)throw trr.error;
    if(d.pool){const pr=await supabase.from('case_pool_members').insert({case_pool_id:d.pool,case_id:cr.data.id});if(pr.error)throw pr.error}
    if(d.source_upload_id)await supabase.from('authoring_uploads').update({import_status:'approved',suggested_target:{organ_system_id:d.organ,chapter_id:d.chapter||null,case_pool_id:d.pool||null,created_case_id:cr.data.id}}).eq('id',d.source_upload_id);
    setMsg(`Gespeichert: ${cr.data.case_code}`);onSaved();
  }catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  return <div className="workbench-overlay"><div className="workbench"><div className="workbench-head"><div><span className="eyebrow">Clinical Case Workbench</span><h2>{d.title_de||'Neuer Clinical Case'}</h2><p>Strukturierte, portable Falllogik für freie Eingaben und deterministische Reaktionen.</p></div><div className="head-actions"><button className="secondary" onClick={exportJson}>JSON exportieren</button><button className="secondary" onClick={onClose}>Schließen</button><button className="primary" disabled={busy} onClick={save}>{busy?'Speichert…':'Als Draft speichern'}</button></div></div>{msg&&<div className="notice">{msg}</div>}
    <div className="tabs"><button className={tab==='builder'?'active':''} onClick={()=>setTab('builder')}>Builder</button><button className={tab==='preview'?'active':''} onClick={()=>setTab('preview')}>App Preview</button><button className={tab==='quality'?'active':''} onClick={()=>setTab('quality')}>Validierung <span className={quality.ok?'badge ok':'badge bad'}>{quality.errors.length}</span></button></div>
    {tab==='quality'&&<div className="quality-panel"><h3>{quality.ok?'Technisch spielbar':'Noch nicht spielbar'}</h3>{quality.errors.map(x=><div className="check bad" key={x}>✕ {x}</div>)}{quality.warnings.map(x=><div className="check warn" key={x}>! {x}</div>)}{quality.ok&&<div className="check ok">✓ Pflichtstruktur vollständig.</div>}<p className="muted">Diese Prüfung validiert Struktur und Vollständigkeit, nicht die medizinische Richtigkeit. Medizinische Inhalte müssen im Review fachlich freigegeben werden.</p></div>}
    {tab==='preview'&&<CasePreview d={d}/>} 
    {tab==='builder'&&<div className="builder-body">
      <EditorSection title="1 · Einordnung" subtitle="Server-Zuordnung, Lernzweck und Region"><div className="grid4"><Field label="Organsystem"><select value={d.organ} onChange={e=>setD(x=>({...x,organ:e.target.value,chapter:'',pool:''}))}><option value="">Auswählen…</option>{organs.map(o=><option key={o.id} value={o.id}>{de(o.organ_system_translations)||o.code}</option>)}</select></Field><Field label="Kapitel"><select value={d.chapter} onChange={e=>setD(x=>({...x,chapter:e.target.value,pool:''}))}><option value="">Kein Kapitel</option>{visibleChapters.map(c=><option key={c.id} value={c.id}>{de(c.chapter_translations)||c.code}</option>)}</select></Field><Field label="Case Pool"><select value={d.pool} onChange={e=>set('pool',e.target.value)}><option value="">Später zuordnen</option>{visiblePools.map(p=><option key={p.id} value={p.id}>{de(p.case_pool_translations)}</option>)}</select></Field><Field label="Scenario ID"><input value={d.scenario} onChange={e=>set('scenario',e.target.value)} placeholder="acute_chest_pain_stemi"/></Field></div><div className="grid4"><Field label="Purpose"><select value={d.purpose} onChange={e=>set('purpose',e.target.value as any)}><option value="practice">Practice</option><option value="curriculum_gate">Curriculum Gate</option><option value="weekly_challenge">Weekly Challenge</option></select></Field><Field label="Schwierigkeit"><input type="number" min="1" max="5" value={d.difficulty} onChange={e=>set('difficulty',Number(e.target.value))}/></Field><Field label="Dauer (min)"><input type="number" value={d.duration} onChange={e=>set('duration',Number(e.target.value))}/></Field><Field label="Medizinische Region"><input value={d.medical_region} onChange={e=>set('medical_region',e.target.value)} placeholder="de-DE"/></Field></div></EditorSection>
      <EditorSection title="2 · Patient und Einstieg"><div className="grid4"><Field label="Alter"><input value={d.age} onChange={e=>set('age',e.target.value)}/></Field><Field label="Geschlecht"><input value={d.sex} onChange={e=>set('sex',e.target.value)}/></Field><Field label="Setting"><input value={d.setting} onChange={e=>set('setting',e.target.value)}/></Field><Field label="Ankunft"><input value={d.arrival_mode} onChange={e=>set('arrival_mode',e.target.value)}/></Field></div><div className="split"><div><h4>Deutsch</h4><Field label="Titel"><input value={d.title_de} onChange={e=>set('title_de',e.target.value)}/></Field><Field label="Leitsymptom"><input value={d.chief_complaint_de} onChange={e=>set('chief_complaint_de',e.target.value)}/></Field><Field label="Patientenvorstellung"><textarea value={d.presentation_de} onChange={e=>set('presentation_de',e.target.value)}/></Field></div><div><h4>English</h4><Field label="Title"><input value={d.title_en} onChange={e=>set('title_en',e.target.value)}/></Field><Field label="Chief complaint"><input value={d.chief_complaint_en} onChange={e=>set('chief_complaint_en',e.target.value)}/></Field><Field label="Patient presentation"><textarea value={d.presentation_en} onChange={e=>set('presentation_en',e.target.value)}/></Field></div></div></EditorSection>
      <EditorSection title="3 · Verborgene medizinische Wahrheit" subtitle="Deterministisch; wird dem Lernenden nicht direkt gezeigt"><div className="grid3"><Field label="Zieldiagnose-ID"><input value={d.target_diagnosis_id} onChange={e=>set('target_diagnosis_id',e.target.value)}/></Field><Field label="Diagnose DE"><input value={d.target_diagnosis_label_de} onChange={e=>set('target_diagnosis_label_de',e.target.value)}/></Field><Field label="Diagnosis EN"><input value={d.target_diagnosis_label_en} onChange={e=>set('target_diagnosis_label_en',e.target.value)}/></Field></div><div className="split"><Field label="Pathophysiologie DE"><textarea value={d.pathophysiology_de} onChange={e=>set('pathophysiology_de',e.target.value)}/></Field><Field label="Pathophysiology EN"><textarea value={d.pathophysiology_en} onChange={e=>set('pathophysiology_en',e.target.value)}/></Field></div><div className="grid2"><Field label="Endpoint Policy"><select value={d.endpoint_policy} onChange={e=>set('endpoint_policy',e.target.value)}><option value="diagnosis_and_treatment">diagnosis_and_treatment</option><option value="treatment_dominant">treatment_dominant</option><option value="diagnosis_only">diagnosis_only</option></select></Field><Field label="Truth Note"><input value={d.case_truth_note} onChange={e=>set('case_truth_note',e.target.value)}/></Field></div></EditorSection>
      <EditorSection title="4 · Hintergrund"><div className="grid3"><Field label="Vorgeschichte / Risikofaktoren (eine Zeile je Eintrag)"><textarea value={d.background} onChange={e=>set('background',e.target.value)}/></Field><Field label="Medikamente"><textarea value={d.medications} onChange={e=>set('medications',e.target.value)}/></Field><Field label="Allergien"><textarea value={d.allergies} onChange={e=>set('allergies',e.target.value)}/></Field></div></EditorSection>
      <EditorSection title="5 · Freie Anamnese" subtitle="Jede Zeile ist ein abrufbares Wissensobjekt. Aliase steuern, welche freie Eingabe es auslösen kann.">{d.history_topics.map((r,i)=><HistoryEditor key={i} r={r} onChange={p=>updateRow<HistoryRow>('history_topics',i,p)} actions={<RowActions onAdd={()=>addRow('history_topics',i,emptyHistory())} onDelete={()=>delRow('history_topics',i)}/>}/>)}</EditorSection>
      <EditorSection title="6 · Untersuchung">{d.examinations.map((r,i)=><ExamEditor key={i} r={r} onChange={p=>updateRow<ExamRow>('examinations',i,p)} actions={<RowActions onAdd={()=>addRow('examinations',i,emptyExam())} onDelete={()=>delRow('examinations',i)}/>}/>)}</EditorSection>
      <EditorSection title="7 · Vitalparameter">{d.vitals.map((r,i)=><div className="repeat-row grid6" key={i}><Field label="measurement_id"><input value={r.measurement_id} onChange={e=>updateRow<VitalRow>('vitals',i,{measurement_id:e.target.value})}/></Field><Field label="Wert"><input value={r.value} onChange={e=>updateRow<VitalRow>('vitals',i,{value:e.target.value})}/></Field><Field label="Einheit"><input value={r.unit} onChange={e=>updateRow<VitalRow>('vitals',i,{unit:e.target.value})}/></Field><Field label="Zeit +s"><input type="number" value={r.time_offset_sec} onChange={e=>updateRow<VitalRow>('vitals',i,{time_offset_sec:Number(e.target.value)})}/></Field><Field label="Relevanz"><select value={r.relevance} onChange={e=>updateRow<VitalRow>('vitals',i,{relevance:e.target.value as any})}>{relevance}</select></Field><RowActions onAdd={()=>addRow('vitals',i,emptyVital())} onDelete={()=>delRow('vitals',i)}/></div>)}</EditorSection>
      <EditorSection title="8 · Diagnostik" subtitle="Freie Anforderungen, deterministische Ergebnisse und optionale Verzögerung">{d.diagnostics.map((r,i)=><DiagnosticEditor key={i} r={r} onChange={p=>updateRow<DiagnosticRow>('diagnostics',i,p)} actions={<RowActions onAdd={()=>addRow('diagnostics',i,emptyDiagnostic())} onDelete={()=>delRow('diagnostics',i)}/>}/>)}</EditorSection>
      <EditorSection title="9 · Differenzialdiagnosen">{d.differential_diagnoses.map((r,i)=><div className="repeat-row grid5" key={i}><Field label="diagnosis_id"><input value={r.diagnosis_id} onChange={e=>updateRow<DifferentialRow>('differential_diagnoses',i,{diagnosis_id:e.target.value})}/></Field><Field label="Label DE"><input value={r.label_de} onChange={e=>updateRow<DifferentialRow>('differential_diagnoses',i,{label_de:e.target.value})}/></Field><Field label="Label EN"><input value={r.label_en} onChange={e=>updateRow<DifferentialRow>('differential_diagnoses',i,{label_en:e.target.value})}/></Field><Field label="Priorität"><input value={r.priority} onChange={e=>updateRow<DifferentialRow>('differential_diagnoses',i,{priority:e.target.value})}/></Field><RowActions onAdd={()=>addRow('differential_diagnoses',i,emptyDifferential())} onDelete={()=>delRow('differential_diagnoses',i)}/></div>)}</EditorSection>
      <EditorSection title="10 · Therapie / Interventionen" subtitle="required markiert für den Fall zwingende Kernaktionen">{d.treatments.map((r,i)=><TreatmentEditor key={i} r={r} onChange={p=>updateRow<TreatmentRow>('treatments',i,p)} actions={<RowActions onAdd={()=>addRow('treatments',i,emptyTreatment())} onDelete={()=>delRow('treatments',i)}/>}/>)}</EditorSection>
      <EditorSection title="11 · Hard Endpoints">{d.hard_endpoints.map((r,i)=><div className="repeat-row grid6" key={i}><Field label="endpoint_id"><input value={r.endpoint_id} onChange={e=>updateRow<EndpointRow>('hard_endpoints',i,{endpoint_id:e.target.value})}/></Field><Field label="Kategorie"><select value={r.category} onChange={e=>updateRow<EndpointRow>('hard_endpoints',i,{category:e.target.value as any})}><option value="diagnosis">diagnosis</option><option value="treatment">treatment</option></select></Field><Field label="Beschreibung DE"><input value={r.description_de} onChange={e=>updateRow<EndpointRow>('hard_endpoints',i,{description_de:e.target.value})}/></Field><Field label="Description EN"><input value={r.description_en} onChange={e=>updateRow<EndpointRow>('hard_endpoints',i,{description_en:e.target.value})}/></Field><Field label="Pflicht"><select value={r.required?'yes':'no'} onChange={e=>updateRow<EndpointRow>('hard_endpoints',i,{required:e.target.value==='yes'})}><option value="yes">required</option><option value="no">optional</option></select></Field><RowActions onAdd={()=>addRow('hard_endpoints',i,emptyEndpoint())} onDelete={()=>delRow('hard_endpoints',i)}/></div>)}</EditorSection>
      <EditorSection title="12 · Lernhilfen und Debrief"><div className="split"><div><h4>Deutsch</h4><Field label="Hints · eine Zeile pro Hint"><textarea value={d.hints_de} onChange={e=>set('hints_de',e.target.value)}/></Field><Field label="Debrief"><textarea value={d.debrief_de} onChange={e=>set('debrief_de',e.target.value)}/></Field><Field label="Lernziele · eine Zeile je Ziel"><textarea value={d.learning_objectives_de} onChange={e=>set('learning_objectives_de',e.target.value)}/></Field></div><div><h4>English</h4><Field label="Hints"><textarea value={d.hints_en} onChange={e=>set('hints_en',e.target.value)}/></Field><Field label="Debrief"><textarea value={d.debrief_en} onChange={e=>set('debrief_en',e.target.value)}/></Field><Field label="Learning objectives"><textarea value={d.learning_objectives_en} onChange={e=>set('learning_objectives_en',e.target.value)}/></Field></div></div><Field label="Interne Autoren-Notizen"><textarea value={d.author_notes} onChange={e=>set('author_notes',e.target.value)}/></Field></EditorSection>
    </div>}</div></div>
}

function HistoryEditor({r,onChange,actions}:{r:HistoryRow;onChange:(p:Partial<HistoryRow>)=>void;actions:any}){return <div className="repeat-card"><div className="grid4"><Field label="topic_id"><input value={r.topic_id} onChange={e=>onChange({topic_id:e.target.value})}/></Field><Field label="Aliase DE · mit | trennen"><input value={r.aliases_de} onChange={e=>onChange({aliases_de:e.target.value})}/></Field><Field label="Aliases EN"><input value={r.aliases_en} onChange={e=>onChange({aliases_en:e.target.value})}/></Field><Field label="Relevanz"><select value={r.relevance} onChange={e=>onChange({relevance:e.target.value as any})}>{relevance}</select></Field></div><div className="split"><Field label="Patientenantwort DE"><textarea value={r.response_de} onChange={e=>onChange({response_de:e.target.value})}/></Field><Field label="Patient response EN"><textarea value={r.response_en} onChange={e=>onChange({response_en:e.target.value})}/></Field></div>{actions}</div>}
function ExamEditor({r,onChange,actions}:{r:ExamRow;onChange:(p:Partial<ExamRow>)=>void;actions:any}){return <div className="repeat-card"><div className="grid4"><Field label="exam_id"><input value={r.exam_id} onChange={e=>onChange({exam_id:e.target.value})}/></Field><Field label="Aliase DE"><input value={r.aliases_de} onChange={e=>onChange({aliases_de:e.target.value})}/></Field><Field label="Aliases EN"><input value={r.aliases_en} onChange={e=>onChange({aliases_en:e.target.value})}/></Field><Field label="Relevanz"><select value={r.relevance} onChange={e=>onChange({relevance:e.target.value as any})}>{relevance}</select></Field></div><div className="split"><Field label="Befund DE"><textarea value={r.finding_de} onChange={e=>onChange({finding_de:e.target.value})}/></Field><Field label="Finding EN"><textarea value={r.finding_en} onChange={e=>onChange({finding_en:e.target.value})}/></Field></div>{actions}</div>}
function DiagnosticEditor({r,onChange,actions}:{r:DiagnosticRow;onChange:(p:Partial<DiagnosticRow>)=>void;actions:any}){return <div className="repeat-card"><div className="grid5"><Field label="diagnostic_id"><input value={r.diagnostic_id} onChange={e=>onChange({diagnostic_id:e.target.value})}/></Field><Field label="Aliase DE"><input value={r.aliases_de} onChange={e=>onChange({aliases_de:e.target.value})}/></Field><Field label="Aliases EN"><input value={r.aliases_en} onChange={e=>onChange({aliases_en:e.target.value})}/></Field><Field label="Delay sec"><input type="number" value={r.delay_sec} onChange={e=>onChange({delay_sec:Number(e.target.value)})}/></Field><Field label="Relevanz"><select value={r.relevance} onChange={e=>onChange({relevance:e.target.value as any})}>{relevance}</select></Field></div><div className="split"><Field label="Resultat DE"><textarea value={r.result_de} onChange={e=>onChange({result_de:e.target.value})}/></Field><Field label="Result EN"><textarea value={r.result_en} onChange={e=>onChange({result_en:e.target.value})}/></Field></div>{actions}</div>}
function TreatmentEditor({r,onChange,actions}:{r:TreatmentRow;onChange:(p:Partial<TreatmentRow>)=>void;actions:any}){return <div className="repeat-card"><div className="grid5"><Field label="action_id"><input value={r.action_id} onChange={e=>onChange({action_id:e.target.value})}/></Field><Field label="Aliase DE"><input value={r.aliases_de} onChange={e=>onChange({aliases_de:e.target.value})}/></Field><Field label="Aliases EN"><input value={r.aliases_en} onChange={e=>onChange({aliases_en:e.target.value})}/></Field><Field label="Pflicht"><select value={r.required?'yes':'no'} onChange={e=>onChange({required:e.target.value==='yes'})}><option value="no">optional</option><option value="yes">required</option></select></Field><Field label="Notiz"><input value={r.notes} onChange={e=>onChange({notes:e.target.value})}/></Field></div><div className="split"><Field label="Effekt DE"><textarea value={r.effect_de} onChange={e=>onChange({effect_de:e.target.value})}/></Field><Field label="Effect EN"><textarea value={r.effect_en} onChange={e=>onChange({effect_en:e.target.value})}/></Field></div>{actions}</div>}

function CasePreview({d}:{d:CaseDraft}){const[hq,setHq]=useState('');const[answers,setAnswers]=useState<string[]>([]);const ask=()=>{const q=hq.trim().toLowerCase();if(!q)return;const all=[...d.history_topics.map(x=>({aliases:x.aliases_de,text:x.response_de})),...d.examinations.map(x=>({aliases:x.aliases_de,text:x.finding_de})),...d.diagnostics.map(x=>({aliases:x.aliases_de,text:x.result_de}))];const found=all.find(x=>x.aliases.split('|').some(a=>a.trim()&&q.includes(a.trim().toLowerCase())));setAnswers(a=>[...a,`› ${hq}`,found?.text||'Für diese freie Eingabe ist in diesem Case noch keine deterministische Antwort hinterlegt.']);setHq('')};return <div className="preview-shell"><div className="phone"><div className="phone-top"><b>{d.title_de||'Clinical Case'}</b><span>Freies Lernen · Preview</span></div><div className="patient-card"><span>Patient</span><p>{d.presentation_de||'Noch keine Patientenvorstellung.'}</p></div><div className="conversation">{answers.map((x,i)=><div key={i} className={x.startsWith('›')?'learner':'patient'}>{x}</div>)}</div><div className="free-input"><input value={hq} onChange={e=>setHq(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="z. B. RR, EKG, Schmerzbeginn…"/><button onClick={ask}>Senden</button></div><div className="preview-footer"><span>{d.history_topics.filter(x=>x.topic_id).length} Anamnese</span><span>{d.diagnostics.filter(x=>x.diagnostic_id).length} Diagnostik</span><span>{d.hard_endpoints.filter(x=>x.endpoint_id).length} Endpoints</span></div></div><div className="preview-explain"><h3>Was diese Preview prüft</h3><p>Freie Texteingaben werden gegen die im Fall hinterlegten Aliase aufgelöst. Es wird keine medizinische Antwort erfunden. Nicht hinterlegte Anfragen liefern bewusst keine Fallinformation.</p><h4>Beispiele</h4><div className="chips">{[...d.history_topics,...d.examinations,...d.diagnostics].flatMap((x:any)=>String(x.aliases_de||'').split('|')).filter(Boolean).slice(0,12).map((x,i)=><button key={i} onClick={()=>setHq(x.trim())}>{x.trim()}</button>)}</div></div></div>}
