import { useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';

type Tab='chapters'|'learning'|'weekly'|'resolver';
const de=(rows:any[]=[])=>rows.find((x:any)=>x.locale==='de')||rows[0];
const en=(rows:any[]=[])=>rows.find((x:any)=>x.locale==='en');

export default function ContentStudio({onClose}:{onClose:()=>void}){
  const[tab,setTab]=useState<Tab>('chapters'); const[msg,setMsg]=useState(''); const[busy,setBusy]=useState(false);
  const[organs,setOrgans]=useState<any[]>([]); const[levels,setLevels]=useState<any[]>([]); const[chapters,setChapters]=useState<any[]>([]); const[pools,setPools]=useState<any[]>([]);
  const[items,setItems]=useState<any[]>([]); const[weeklies,setWeeklies]=useState<any[]>([]); const[lexicons,setLexicons]=useState<any[]>([]); const[aliases,setAliases]=useState<any[]>([]);
  const[editChapter,setEditChapter]=useState<any|null>(null); const[editItem,setEditItem]=useState<any|null>(null); const[editWeekly,setEditWeekly]=useState<any|null>(null); const[editLex,setEditLex]=useState<any|null>(null);

  const load=async()=>{const[o,l,c,p,i,w,x,a]=await Promise.all([
    supabase.from('organ_systems').select('id,code,organ_system_translations(locale,name)').order('sequence'),
    supabase.from('curriculum_levels').select('id,organ_system_id,code,sequence,curriculum_level_translations(locale,title)').order('sequence'),
    supabase.from('chapters').select('*,chapter_translations(*)').neq('status','archived').order('sequence'),
    supabase.from('case_pools').select('id,organ_system_id,chapter_id,purpose,status,case_pool_translations(locale,title)').order('created_at'),
    supabase.from('content_items').select('*,content_translations(*)').neq('status','archived').order('updated_at',{ascending:false}),
    supabase.from('weekly_cases').select('*,weekly_case_translations(*)').order('week_start',{ascending:false}),
    supabase.from('resolver_lexicons').select('*').order('locale').order('version',{ascending:false}),
    supabase.from('resolver_aliases').select('*').order('action_id').order('priority',{ascending:false})
  ]);setOrgans(o.data||[]);setLevels(l.data||[]);setChapters(c.data||[]);setPools(p.data||[]);setItems(i.data||[]);setWeeklies(w.data||[]);setLexicons(x.data||[]);setAliases(a.data||[])};
  useEffect(()=>{load()},[]);
  const resetMsg=()=>setMsg('');

  const newChapter=()=>setEditChapter({id:null,organ_system_id:'',level_id:'',code:'',sequence:1,title_de:'',subtitle_de:'',title_en:'',subtitle_en:''});
  const openChapter=(c:any)=>setEditChapter({id:c.id,organ_system_id:c.organ_system_id,level_id:c.level_id,code:c.code,sequence:c.sequence,title_de:de(c.chapter_translations)?.title||'',subtitle_de:de(c.chapter_translations)?.subtitle||'',title_en:en(c.chapter_translations)?.title||'',subtitle_en:en(c.chapter_translations)?.subtitle||''});
  const saveChapter=async()=>{if(!editChapter)return;setBusy(true);resetMsg();try{let id=editChapter.id;if(id){const r=await supabase.from('chapters').update({organ_system_id:editChapter.organ_system_id,level_id:editChapter.level_id,code:editChapter.code,sequence:Number(editChapter.sequence),updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error}else{const r=await supabase.from('chapters').insert({organ_system_id:editChapter.organ_system_id,level_id:editChapter.level_id,code:editChapter.code,sequence:Number(editChapter.sequence),status:'draft'}).select('id').single();if(r.error)throw r.error;id=r.data.id}
    for(const [locale,title,subtitle] of [['de',editChapter.title_de,editChapter.subtitle_de],['en',editChapter.title_en,editChapter.subtitle_en]] as any[]){if(!title)continue;const r=await supabase.from('chapter_translations').upsert({chapter_id:id,locale,title,subtitle:subtitle||null,status:'draft'},{onConflict:'chapter_id,locale'});if(r.error)throw r.error}setMsg('Kapitel gespeichert.');setEditChapter(null);await load()}catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  const newItem=()=>setEditItem({id:null,content_code:'',content_type:'knowledge',chapter_id:'',sequence:1,title_de:'',body_de:'',explanation_de:'',title_en:'',body_en:'',explanation_en:'',options:'',answer:''});
  const openItem=async(i:any)=>{const node=await supabase.from('chapter_nodes').select('chapter_id,sequence').eq('content_item_id',i.id).maybeSingle();const d=de(i.content_translations)?.payload||{}, e=en(i.content_translations)?.payload||{};setEditItem({id:i.id,content_code:i.content_code,content_type:i.content_type,chapter_id:node.data?.chapter_id||'',sequence:node.data?.sequence||1,title_de:d.title||'',body_de:d.body||'',explanation_de:d.explanation||'',title_en:e.title||'',body_en:e.body||'',explanation_en:e.explanation||'',options:(i.config?.options||[]).join('\n'),answer:i.config?.answer||''})};
  const saveItem=async()=>{if(!editItem)return;setBusy(true);resetMsg();try{const config:any={};const opts=editItem.options.split('\n').map((x:string)=>x.trim()).filter(Boolean);if(opts.length)config.options=opts;if(editItem.answer.trim())config.answer=editItem.answer.trim();let id=editItem.id;if(id){const r=await supabase.from('content_items').update({content_code:editItem.content_code,content_type:editItem.content_type,config,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error}else{const r=await supabase.from('content_items').insert({content_code:editItem.content_code,content_type:editItem.content_type,config,status:'draft'}).select('id').single();if(r.error)throw r.error;id=r.data.id}
    for(const [locale,title,body,explanation] of [['de',editItem.title_de,editItem.body_de,editItem.explanation_de],['en',editItem.title_en,editItem.body_en,editItem.explanation_en]] as any[]){if(!title)continue;const r=await supabase.from('content_translations').upsert({content_item_id:id,locale,payload:{title,body,explanation:explanation||null},status:'draft'},{onConflict:'content_item_id,locale'});if(r.error)throw r.error}
    if(editItem.chapter_id){const ex=await supabase.from('chapter_nodes').select('id').eq('content_item_id',id).maybeSingle();if(ex.data?.id){const r=await supabase.from('chapter_nodes').update({chapter_id:editItem.chapter_id,sequence:Number(editItem.sequence),node_type:editItem.content_type}).eq('id',ex.data.id);if(r.error)throw r.error}else{const r=await supabase.from('chapter_nodes').insert({chapter_id:editItem.chapter_id,sequence:Number(editItem.sequence),node_type:editItem.content_type,content_item_id:id});if(r.error)throw r.error}}
    setMsg('Lerninhalt gespeichert.');setEditItem(null);await load()}catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  const newWeekly=()=>setEditWeekly({id:null,week_start:'',case_pool_id:'',starts_at:'',ends_at:'',bonus_xp:50,title_de:'',subtitle_de:'',description_de:'',title_en:'',subtitle_en:'',description_en:''});
  const openWeekly=(w:any)=>setEditWeekly({id:w.id,week_start:w.week_start,case_pool_id:w.case_pool_id,starts_at:String(w.starts_at||'').slice(0,16),ends_at:String(w.ends_at||'').slice(0,16),bonus_xp:w.bonus_xp,title_de:de(w.weekly_case_translations)?.title||'',subtitle_de:de(w.weekly_case_translations)?.subtitle||'',description_de:de(w.weekly_case_translations)?.description||'',title_en:en(w.weekly_case_translations)?.title||'',subtitle_en:en(w.weekly_case_translations)?.subtitle||'',description_en:en(w.weekly_case_translations)?.description||''});
  const saveWeekly=async()=>{if(!editWeekly)return;setBusy(true);resetMsg();try{let id=editWeekly.id;const base={week_start:editWeekly.week_start,case_pool_id:editWeekly.case_pool_id,starts_at:new Date(editWeekly.starts_at).toISOString(),ends_at:new Date(editWeekly.ends_at).toISOString(),bonus_xp:Number(editWeekly.bonus_xp),status:'draft'};if(id){const r=await supabase.from('weekly_cases').update(base).eq('id',id);if(r.error)throw r.error}else{const r=await supabase.from('weekly_cases').insert(base).select('id').single();if(r.error)throw r.error;id=r.data.id}
    for(const [locale,title,subtitle,description] of [['de',editWeekly.title_de,editWeekly.subtitle_de,editWeekly.description_de],['en',editWeekly.title_en,editWeekly.subtitle_en,editWeekly.description_en]] as any[]){if(!title)continue;const r=await supabase.from('weekly_case_translations').upsert({weekly_case_id:id,locale,title,subtitle:subtitle||null,description:description||null},{onConflict:'weekly_case_id,locale'});if(r.error)throw r.error}setMsg('Case of the Week gespeichert.');setEditWeekly(null);await load()}catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  const newLex=()=>setEditLex({id:null,locale:'de',version:1,minimum_app_version:'',rows:[{action_id:'',alias:'',context:'global',priority:100,is_active:true}]});
  const openLex=(x:any)=>setEditLex({id:x.id,locale:x.locale,version:x.version,minimum_app_version:x.minimum_app_version||'',rows:aliases.filter(a=>a.lexicon_id===x.id).map(a=>({...a}))});
  const saveLex=async()=>{if(!editLex)return;setBusy(true);resetMsg();try{let id=editLex.id;if(id){const r=await supabase.from('resolver_lexicons').update({locale:editLex.locale,version:Number(editLex.version),minimum_app_version:editLex.minimum_app_version||null}).eq('id',id);if(r.error)throw r.error;const d=await supabase.from('resolver_aliases').delete().eq('lexicon_id',id);if(d.error)throw d.error}else{const r=await supabase.from('resolver_lexicons').insert({locale:editLex.locale,version:Number(editLex.version),minimum_app_version:editLex.minimum_app_version||null,status:'draft'}).select('id').single();if(r.error)throw r.error;id=r.data.id}
    const rows=editLex.rows.filter((r:any)=>r.action_id.trim()&&r.alias.trim()).map((r:any)=>({lexicon_id:id,action_id:r.action_id.trim(),alias:r.alias.trim(),context:r.context||'global',priority:Number(r.priority)||100,is_active:r.is_active!==false}));if(rows.length){const r=await supabase.from('resolver_aliases').insert(rows);if(r.error)throw r.error}setMsg('Resolver-Lexikon gespeichert.');setEditLex(null);await load()}catch(e:any){setMsg(e.message||String(e))}finally{setBusy(false)}};

  const visibleLevels=useMemo(()=>levels.filter(l=>!editChapter?.organ_system_id||l.organ_system_id===editChapter.organ_system_id),[levels,editChapter]);
  const weeklyPools=pools.filter(p=>p.purpose==='weekly_challenge');
  return <div className="studio-overlay"><div className="studio-shell"><header className="studio-head"><div><span className="eyebrow">Medilingo Content Studio</span><h2>Inhalte erstellen & aktualisieren</h2><p>Kapitel, Wissensblöcke, Fragen, Flashcards, Weekly Cases und Resolver an einem Ort.</p></div><button className="secondary" onClick={onClose}>Schließen</button></header>{msg&&<div className="notice studio-notice">{msg}</div>}<div className="studio-tabs">{([['chapters','Kapitel'],['learning','Lerninhalte'],['weekly','Case of the Week'],['resolver','Resolver']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='chapters'&&<Manager title="Kapitel" onNew={newChapter}>{chapters.map(c=><Entry key={c.id} title={de(c.chapter_translations)?.title||c.code} meta={`${c.code} · ${c.status}`} onEdit={()=>openChapter(c)}/>)}</Manager>}
  {tab==='learning'&&<Manager title="Wissensblöcke, Fragen & Flashcards" onNew={newItem}>{items.map(i=><Entry key={i.id} title={de(i.content_translations)?.payload?.title||i.content_code} meta={`${i.content_type} · ${i.content_code} · ${i.status}`} onEdit={()=>openItem(i)}/>)}</Manager>}
  {tab==='weekly'&&<Manager title="Case of the Week" onNew={newWeekly}>{weeklies.map(w=><Entry key={w.id} title={de(w.weekly_case_translations)?.title||w.week_start} meta={`${w.week_start} · ${w.status} · ${w.bonus_xp} XP`} onEdit={()=>openWeekly(w)}/>)}</Manager>}
  {tab==='resolver'&&<Manager title="Resolver-Lexika" onNew={newLex}>{lexicons.map(x=><Entry key={x.id} title={`${x.locale} · v${x.version}`} meta={`${aliases.filter(a=>a.lexicon_id===x.id).length} Aliase · ${x.status}`} onEdit={()=>openLex(x)}/>)}</Manager>}
  {editChapter&&<Modal title={editChapter.id?'Kapitel bearbeiten':'Kapitel erstellen'} onClose={()=>setEditChapter(null)} onSave={saveChapter} busy={busy}><div className="grid2"><label>Organsystem<select value={editChapter.organ_system_id} onChange={e=>setEditChapter({...editChapter,organ_system_id:e.target.value,level_id:''})}><option value="">Auswählen</option>{organs.map(o=><option key={o.id} value={o.id}>{de(o.organ_system_translations)?.name||o.code}</option>)}</select></label><label>Level<select value={editChapter.level_id} onChange={e=>setEditChapter({...editChapter,level_id:e.target.value})}><option value="">Auswählen</option>{visibleLevels.map(l=><option key={l.id} value={l.id}>{de(l.curriculum_level_translations)?.title||l.code}</option>)}</select></label><label>Code<input value={editChapter.code} onChange={e=>setEditChapter({...editChapter,code:e.target.value})}/></label><label>Reihenfolge<input type="number" value={editChapter.sequence} onChange={e=>setEditChapter({...editChapter,sequence:e.target.value})}/></label></div><LocaleFields x={editChapter} set={setEditChapter} titleOnly/></Modal>}
  {editItem&&<Modal title={editItem.id?'Lerninhalt bearbeiten':'Lerninhalt erstellen'} onClose={()=>setEditItem(null)} onSave={saveItem} busy={busy}><div className="grid3"><label>Typ<select value={editItem.content_type} onChange={e=>setEditItem({...editItem,content_type:e.target.value})}><option value="knowledge">Wissensblock</option><option value="multiple_choice">Multiple Choice</option><option value="flashcards">Flashcards</option><option value="free_answer">Free Answer</option><option value="checkpoint">Checkpoint</option><option value="multimedia">Multimedia</option><option value="milestone">Milestone</option><option value="level_milestone">Level Milestone</option></select></label><label>Content-Code<input value={editItem.content_code} onChange={e=>setEditItem({...editItem,content_code:e.target.value})}/></label><label>Kapitel<select value={editItem.chapter_id} onChange={e=>setEditItem({...editItem,chapter_id:e.target.value})}><option value="">Nicht zugeordnet</option>{chapters.map(c=><option key={c.id} value={c.id}>{de(c.chapter_translations)?.title||c.code}</option>)}</select></label></div><LocaleFields x={editItem} set={setEditItem}/><div className="grid2"><label>Optionen / Karten · eine pro Zeile<textarea value={editItem.options} onChange={e=>setEditItem({...editItem,options:e.target.value})}/></label><label>Korrekte Antwort / Konzept<input value={editItem.answer} onChange={e=>setEditItem({...editItem,answer:e.target.value})}/></label></div></Modal>}
  {editWeekly&&<Modal title={editWeekly.id?'Weekly bearbeiten':'Weekly erstellen'} onClose={()=>setEditWeekly(null)} onSave={saveWeekly} busy={busy}><div className="grid3"><label>Wochenstart<input type="date" value={editWeekly.week_start} onChange={e=>setEditWeekly({...editWeekly,week_start:e.target.value})}/></label><label>Weekly Case Pool<select value={editWeekly.case_pool_id} onChange={e=>setEditWeekly({...editWeekly,case_pool_id:e.target.value})}><option value="">Auswählen</option>{weeklyPools.map(p=><option key={p.id} value={p.id}>{de(p.case_pool_translations)?.title||p.id}</option>)}</select></label><label>Bonus XP<input type="number" value={editWeekly.bonus_xp} onChange={e=>setEditWeekly({...editWeekly,bonus_xp:e.target.value})}/></label><label>Start<input type="datetime-local" value={editWeekly.starts_at} onChange={e=>setEditWeekly({...editWeekly,starts_at:e.target.value})}/></label><label>Ende<input type="datetime-local" value={editWeekly.ends_at} onChange={e=>setEditWeekly({...editWeekly,ends_at:e.target.value})}/></label></div><LocaleFields x={editWeekly} set={setEditWeekly} weekly/></Modal>}
  {editLex&&<Modal title={editLex.id?'Resolver bearbeiten':'Resolver erstellen'} onClose={()=>setEditLex(null)} onSave={saveLex} busy={busy}><div className="grid3"><label>Locale<input value={editLex.locale} onChange={e=>setEditLex({...editLex,locale:e.target.value})} placeholder="de"/></label><label>Version<input type="number" value={editLex.version} onChange={e=>setEditLex({...editLex,version:e.target.value})}/></label><label>Minimum App Version<input value={editLex.minimum_app_version} onChange={e=>setEditLex({...editLex,minimum_app_version:e.target.value})}/></label></div><h3>Aliase</h3>{editLex.rows.map((r:any,idx:number)=><div className="alias-row" key={idx}><input placeholder="action_id" value={r.action_id} onChange={e=>{const rows=[...editLex.rows];rows[idx]={...r,action_id:e.target.value};setEditLex({...editLex,rows})}}/><input placeholder="Alias" value={r.alias} onChange={e=>{const rows=[...editLex.rows];rows[idx]={...r,alias:e.target.value};setEditLex({...editLex,rows})}}/><input placeholder="Kontext" value={r.context} onChange={e=>{const rows=[...editLex.rows];rows[idx]={...r,context:e.target.value};setEditLex({...editLex,rows})}}/><input type="number" value={r.priority} onChange={e=>{const rows=[...editLex.rows];rows[idx]={...r,priority:e.target.value};setEditLex({...editLex,rows})}}/><button className="secondary" onClick={()=>setEditLex({...editLex,rows:editLex.rows.filter((_:any,i:number)=>i!==idx)})}>−</button></div>)}<button className="secondary" onClick={()=>setEditLex({...editLex,rows:[...editLex.rows,{action_id:'',alias:'',context:'global',priority:100,is_active:true}]})}>＋ Alias</button></Modal>}
  </div></div>
}
function Manager({title,onNew,children}:{title:string,onNew:()=>void,children:any}){return <main className="studio-body"><div className="studio-title"><h3>{title}</h3><button className="primary" onClick={onNew}>＋ Neu erstellen</button></div><div className="studio-list">{children}</div></main>}
function Entry({title,meta,onEdit}:{title:string,meta:string,onEdit:()=>void}){return <div className="studio-entry"><div><b>{title}</b><span>{meta}</span></div><button className="secondary" onClick={onEdit}>Bearbeiten / Update</button></div>}
function Modal({title,onClose,onSave,busy,children}:{title:string,onClose:()=>void,onSave:()=>void,busy:boolean,children:any}){return <div className="modal-bg studio-modal-bg"><div className="modal"><div className="modal-title"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}<div className="actions"><button className="secondary" onClick={onClose}>Abbrechen</button><button className="primary" disabled={busy} onClick={onSave}>{busy?'Speichert…':'Speichern'}</button></div></div></div>}
function LocaleFields({x,set,titleOnly=false,weekly=false}:{x:any,set:(v:any)=>void,titleOnly?:boolean,weekly?:boolean}){return <div className="split"><div><h3>Deutsch</h3><label>Titel<input value={x.title_de||''} onChange={e=>set({...x,title_de:e.target.value})}/></label>{!titleOnly&&<label>{weekly?'Beschreibung':'Inhalt'}<textarea value={(weekly?x.description_de:x.body_de)||''} onChange={e=>set({...x,[weekly?'description_de':'body_de']:e.target.value})}/></label>}{!weekly&&!titleOnly&&<label>Erklärung<textarea value={x.explanation_de||''} onChange={e=>set({...x,explanation_de:e.target.value})}/></label>}{weekly&&<label>Untertitel<input value={x.subtitle_de||''} onChange={e=>set({...x,subtitle_de:e.target.value})}/></label>}{titleOnly&&<label>Untertitel<input value={x.subtitle_de||''} onChange={e=>set({...x,subtitle_de:e.target.value})}/></label>}</div><div><h3>English</h3><label>Title<input value={x.title_en||''} onChange={e=>set({...x,title_en:e.target.value})}/></label>{!titleOnly&&<label>{weekly?'Description':'Content'}<textarea value={(weekly?x.description_en:x.body_en)||''} onChange={e=>set({...x,[weekly?'description_en':'body_en']:e.target.value})}/></label>}{!weekly&&!titleOnly&&<label>Explanation<textarea value={x.explanation_en||''} onChange={e=>set({...x,explanation_en:e.target.value})}/></label>}{weekly&&<label>Subtitle<input value={x.subtitle_en||''} onChange={e=>set({...x,subtitle_en:e.target.value})}/></label>}{titleOnly&&<label>Subtitle<input value={x.subtitle_en||''} onChange={e=>set({...x,subtitle_en:e.target.value})}/></label>}</div></div>}
