import { useState } from 'react';
import { supabase } from './lib/supabase';
import { CaseDraft, draftFromParsed } from './caseTypes';

type Upload={id:string;original_filename:string;mime_type:string|null;import_status:string;detected_type:string|null;parser_output?:any;validation_report?:any;suggested_target?:any;error_message?:string|null;created_at:string};
type Props={uploads:Upload[];profileId:string;canAuthor:boolean;onRefresh:()=>Promise<void>|void;onOpenDraft:(draft:CaseDraft)=>void};

const statusLabel:Record<string,string>={uploaded:'Hochgeladen',parsing:'Wird gelesen',parsed:'Geparst',validation_failed:'Validierung fehlgeschlagen',ready_for_review:'Bereit für Review',approved:'Als Draft übernommen',published:'Veröffentlicht',rejected:'Abgelehnt'};

export default function ImportReview({uploads,profileId,canAuthor,onRefresh,onOpenDraft}:Props){
 const[busy,setBusy]=useState<string|null>(null);const[msg,setMsg]=useState('');const[selected,setSelected]=useState<Upload|null>(null);
 const upload=async(e:any)=>{const file=e.target.files?.[0];if(!file||!canAuthor)return;setBusy('upload');setMsg('');try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${profileId}/${Date.now()}-${safe}`;const up=await supabase.storage.from('authoring-uploads').upload(path,file,{contentType:file.type||undefined,upsert:false});if(up.error)throw up.error;const n=file.name.toLowerCase();const detected=n.endsWith('.docx')?'docx':(n.endsWith('.xlsx')||n.endsWith('.xls'))?'spreadsheet':n.endsWith('.pdf')?'pdf':'document';const r=await supabase.from('authoring_uploads').insert({uploaded_by:profileId,original_filename:file.name,storage_path:path,mime_type:file.type||null,detected_type:detected,import_status:'uploaded'});if(r.error)throw r.error;setMsg('Datei hochgeladen. Du kannst sie jetzt parsen und validieren.');await onRefresh();}catch(err:any){setMsg(err.message||String(err))}finally{setBusy(null);e.target.value=''}};
 const parse=async(u:Upload)=>{setBusy(u.id);setMsg('');try{const{data,error}=await supabase.functions.invoke('parse-authoring-upload',{body:{upload_id:u.id}});if(error)throw error;if(data?.error)throw new Error(data.error);setMsg(data.status==='ready_for_review'?'Dokument verstanden und technisch validiert. Review ist bereit.':'Parser abgeschlossen; bitte Validierungsfehler prüfen.');await onRefresh();if(selected?.id===u.id){const{data:full}=await supabase.from('authoring_uploads').select('*').eq('id',u.id).single();if(full)setSelected(full as any)}}catch(e:any){setMsg(e.message||String(e));await onRefresh()}finally{setBusy(null)}};
 const open=async(u:Upload)=>{const{data,error}=await supabase.from('authoring_uploads').select('*').eq('id',u.id).single();if(error){setMsg(error.message);return}setSelected(data as any)};
 const toBuilder=(u:Upload)=>{if(!u.parser_output)return;const parsed={...u.parser_output,source_upload_id:u.id};onOpenDraft(draftFromParsed(parsed,u.suggested_target||{}));setSelected(null)};
 return <><header><div><h1>Upload Inbox</h1><p>Upload → Parser → technische Validierung → Review → Case Builder → App Preview.</p></div><label className={`upload-button ${!canAuthor?'disabled':''}`}>{busy==='upload'?'Lädt hoch…':'＋ Dokument hochladen'}<input disabled={!canAuthor||busy==='upload'} type="file" accept=".docx,.xlsx,.xls,.pdf,.txt,.csv" onChange={upload}/></label></header>{msg&&<div className="notice">{msg}</div>}<div className="pipeline"><span>1 Upload</span><b>→</b><span>2 Parse</span><b>→</b><span>3 Validate</span><b>→</b><span>4 Review</span><b>→</b><span>5 Case Draft</span></div><div className="card"><div className="import-table"><div className="import-row head"><span>Datei</span><span>Typ</span><span>Status</span><span>Aktion</span></div>{uploads.length===0?<div className="empty">Noch keine Uploads.</div>:uploads.map(u=><div className="import-row" key={u.id}><div><b>{u.original_filename}</b><small>{new Date(u.created_at).toLocaleString()}</small></div><span>{u.detected_type||'—'}</span><span><i className={`status-dot ${u.import_status}`}></i>{statusLabel[u.import_status]||u.import_status}</span><div className="inline-actions">{['uploaded','validation_failed'].includes(u.import_status)&&<button disabled={busy===u.id} className="primary mini-btn" onClick={()=>parse(u)}>{busy===u.id?'Liest…':'Parsen & validieren'}</button>}<button className="secondary mini-btn" onClick={()=>open(u)}>Details</button></div></div>)}</div></div>
 {selected&&<ReviewDrawer upload={selected} onClose={()=>setSelected(null)} onParse={()=>parse(selected)} onBuilder={()=>toBuilder(selected)}/>}</>;
}

function ReviewDrawer({upload,onClose,onParse,onBuilder}:{upload:Upload;onClose:()=>void;onParse:()=>void;onBuilder:()=>void}){const r=upload.validation_report;const d=upload.parser_output;return <div className="drawer-bg"><aside className="review-drawer"><div className="drawer-head"><div><span className="eyebrow">Import Review</span><h2>{upload.original_filename}</h2></div><button onClick={onClose}>×</button></div><div className="status-banner"><b>{statusLabel[upload.import_status]||upload.import_status}</b><span>{upload.error_message||'Parser- und Validierungsdaten werden hier nachvollziehbar angezeigt.'}</span></div>{!d&&<div className="empty-box"><h3>Noch nicht geparst</h3><p>Die Datei ist gespeichert, aber noch nicht in Medilingo-Felder zerlegt.</p><button className="primary" onClick={onParse}>Jetzt parsen & validieren</button></div>}{r&&<section><h3>Technische Validierung</h3><div className="validation-summary"><div><b>{r.errors?.length||0}</b><span>Fehler</span></div><div><b>{r.warnings?.length||0}</b><span>Warnungen</span></div><div><b>{r.stats?.diagnostics||0}</b><span>Diagnostik</span></div><div><b>{r.stats?.hard_endpoints||0}</b><span>Endpoints</span></div></div>{r.checks?.map((c:any)=><div className={`check ${c.ok?'ok':c.severity==='warning'?'warn':'bad'}`} key={c.code}>{c.ok?'✓':'!'} {c.label}</div>)}</section>}{d&&<><section><h3>Was wurde verstanden?</h3><div className="understood-grid"><Info label="Scenario" value={d.meta?.scenario_code}/><Info label="Organsystem" value={d.meta?.organ_system_code}/><Info label="Kapitel" value={d.meta?.chapter_code}/><Info label="Zieldiagnose" value={d.medical_logic?.target_diagnosis_id}/><Info label="Anamnese-Topics" value={String(d.medical_logic?.history_topics?.length||0)}/><Info label="Untersuchungen" value={String(d.medical_logic?.examinations?.length||0)}/><Info label="Vitalwerte" value={String(d.medical_logic?.vitals?.length||0)}/><Info label="Diagnostik" value={String(d.medical_logic?.diagnostics?.length||0)}/><Info label="Therapieaktionen" value={String(d.medical_logic?.treatments?.length||0)}/><Info label="Hard Endpoints" value={String(d.medical_logic?.hard_endpoints?.length||0)}/></div></section><section><h3>Patientenvorschau</h3><div className="patient-card"><b>{d.localized?.de?.title}</b><p>{d.localized?.de?.patient_presentation}</p></div></section><section><h3>Extrahierte Struktur</h3><details><summary>Strukturiertes Parser-JSON anzeigen</summary><pre className="json-view">{JSON.stringify(d,null,2)}</pre></details></section><div className="drawer-actions"><button className="secondary" onClick={onClose}>Schließen</button><button className="primary" disabled={!r?.ok} onClick={onBuilder}>Im Case Builder prüfen</button></div></>}</aside></div>}
function Info({label,value}:{label:string;value:any}){return <div className="info-tile"><span>{label}</span><b>{value||'—'}</b></div>}
